feat: added goroutines to aws fetcher
tailwarden/komiser pull request #1006
Opened 2023-09-27 13:30 UTC by AvineshTripathi

fixes #1014 

This PR is a part of ongoing efforts made to optimize the architecture komiser currently has. 

With this PR duration to fetch aws resources is decreased significantly. 

I would recommed to test this with multipile accounts and compare the durations but mainly check if there is any conflicts in db due to this!

2023-09-27 14:21 UTC, Azanul requested changes
Please look in worker pools as several go routine creatine would lead to resource exhaustion and increased latency. I think we'll be using the same method for concurrency everywhere. 
Better a feature now than a bug later. I'd also like to know your thoughts on this, did you consider this or any other method to avoid issues commonly associated with concurrency?

2023-09-27 14:21 UTC, Azanul commented on providers/aws/aws.go
> +					log.Warnf("[%s][AWS] %s", client.Name, err)
Another parameter should be added to the log to precisely identify where the error/warning/info is from. With the current one we won't be able to determine while fetching which resource the log has been logged.

2023-09-28 03:44 UTC, AvineshTripathi commented on providers/aws/aws.go
> +					log.Warnf("[%s][AWS] %s", client.Name, err)
Totally agreeing to what you said about worker pools however I was confused to what level the division of job should we do based on current architecture. We will have something similar to other providers too and also I would really want to avoid to much os nested routines. Would love to know your thoughts on that?

p.s. This PR is just an entrypoint to a discussion that I wanted to start with folks!

2023-09-28 05:42 UTC, Azanul commented
> Totally agreeing to what you said about worker pools however I was confused to what level the division of job should we do based on current architecture. We will have something similar to other providers too and also I would really want to avoid to much of nested routines. Would love to know your thoughts on that?
> 

Regarding nesting goroutines, it's about the use-case, we'd want to nest go routines to get the best performance out of our application.
I'm thinking 3 levels, provider -> resource -> required APIs, where resource goroutine will be pooled at application level.

2023-09-28 07:50 UTC, AvineshTripathi commented
Can you create a rough draft of what you have in your mind! We can work together if you want

2023-09-28 11:50 UTC, Azanul commented
> Can you create a rough draft of what you have in your mind! We can work together if you want

Sure, we can work together. What do you mean by a rough draft? a PoC would be easier to do than diagrams & documents.

2023-09-28 14:02 UTC, AvineshTripathi commented
> > Can you create a rough draft of what you have in your mind! We can work together if you want
> 
> Sure, we can work together. What do you mean by a rough draft? a PoC would be easier to do than diagrams & documents.

Anything you are comfortable with I want to document it to track thing and keep the discussion somewhere for future reference

2023-09-29 16:06 UTC, Azanul commented
>Anything you are comfortable with I want to document it to track thing and keep the discussion somewhere for future reference

We can continue the discussion in a GH issue or a GH discussion or someplace else. I think a GH discussion would be the right place for it but I don't really have a preference in this matter.
cc: @mlabouardy

2023-10-02 19:24 UTC, mlabouardy commented
> > Anything you are comfortable with I want to document it to track thing and keep the discussion somewhere for future reference
> 
> We can continue the discussion in a GH issue or a GH discussion or someplace else. I think a GH discussion would be the right place for it but I don't really have a preference in this matter. cc: @mlabouardy

I agree, this is a good starting point: https://github.com/tailwarden/komiser/issues/1014

2023-10-10 08:56 UTC, AvineshTripathi commented
Setting down this PR as it served its duty to give rise to #1065 O7!

2023-10-10 08:56 UTC, closed without merging