fix: improve cose-bilkent layout parameters
tailwarden/komiser pull request #1011
Opened 2023-09-29 13:35 UTC by Traxmaxx

## Problem

Bigger graphs look a little bit odd sometimes and I want to get closer to the original designs

## Solution

I changes some of the layout parameters (coent-bilkent) to get closer to the designs when rendering the graph.

Before:
![Screenshot 2023-09-29 at 15 26 44](https://github.com/tailwarden/komiser/assets/320272/d344ddc5-eb6e-4c33-9a64-668b28d40a1d)

after:
![Screenshot 2023-09-29 at 15 33 53](https://github.com/tailwarden/komiser/assets/320272/9836d244-15f9-4b6c-b50e-2b392794e206)

## Changes Made

See diff

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-09-29 18:20 UTC, AvineshTripathi approved these changes
LGTM

2023-09-30 07:27 UTC, shivam-sharma7 approved these changes

2023-10-02 00:26 UTC, shivam-sharma7 commented on dashboard/components/explorer/DependencyGraph.tsx
> +      <div className="absolute bottom-0 left-0 flex gap-2 overflow-visible overflow-visible bg-black-100 text-black-400">
```suggestion
      <div className="absolute bottom-0 left-0 flex gap-2 overflow-visible bg-black-100 text-black-400">
```

2023-10-02 00:27 UTC, shivam-sharma7 requested changes

2023-10-02 00:27 UTC, shivam-sharma7 commented on dashboard/components/explorer/DependencyGraph.tsx
> +      <div className="absolute bottom-0 left-0 flex gap-2 overflow-visible overflow-visible bg-black-100 text-black-400">
keep one

2023-10-02 10:04 UTC, Traxmaxx commented
I added some more improvements based on feedback from @AllieMendes and @jakepage91 (thanks a lot 🙏)

Show full name on hover and also show relation type on hovering edges. Additionally we now show the total resource count in the bottom left corner and there's a tooltip which explains we just display AWS infrastructure for the interim period.
![Screenshot 2023-10-02 at 12 00 13](https://github.com/tailwarden/komiser/assets/320272/66f2bc52-673f-4534-9692-5fea8cdf1e28)
![Screenshot 2023-10-02 at 12 00 17](https://github.com/tailwarden/komiser/assets/320272/17ee30c8-f347-4ab5-931d-a38983011778)
![Screenshot 2023-10-02 at 12 00 25](https://github.com/tailwarden/komiser/assets/320272/666be43e-b21c-4151-a95b-2fd8bb7bf57b)

2023-10-02 11:50 UTC, shivam-sharma7 commented
@Traxmaxx This is amazing

2023-10-02 11:50 UTC, shivam-sharma7 approved these changes

2023-10-02 19:27 UTC, mlabouardy approved these changes

2023-10-02 19:27 UTC, merged