[Feature] Enhancing the Contributing Guide
tailwarden/komiser pull request #1034
Opened 2023-10-04 13:11 UTC by verma-kunal

With this PR, the existing contributing guide has been revamped with the focus on guiding new contributors on the right path to get involved in the Komiser project!

## Few noticeable items added:

- more structured
- different ways to contribute (Komiser Engine & UI)
- best practices while contributing

## Reviewers
@jakepage91 @AvineshTripathi 

Fixes #1029

2023-10-04 14:00 UTC, jakepage91 requested changes
Hey there @verma-kunal great work here! I've added a few thoughts

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +**Planning to work on adding a major feature enhancement?** That's amazing and we always recommend discussing your plans with the team first.
Maybe we can change slightly to "That's amazing we always encourage ambitious contributions. Keep in mind though that we always recommend discussing your plans with the team first."

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +Before diving into contributions, here are a few things to keep in mind:
How about "Before getting started with your first contribution"

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +> ### Keeping your Fork Up-to-Date
Is there is a reason for this whole section to be quoted?

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +6. While submitting Pull Request, **make sure to change the base branch from**: [master](https://github.com/tailwarden/komiser/tree/master) to [develop](v). This will ensure to keep your Pull Request
We can change to "When submitting you Pull Request, **make sure to change the base branch from**: [master](https://github.com/tailwarden/komiser/tree/master) to [develop](v). Making sure to avoid any possible merge conflicts"

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +You may follow the instructions given in the [documentation](https://docs.komiser.io/getting-started/installation) to install the **Komiser CLI**, according to your operating system.
Let's remove "You may" and start the sentence with "Follow the instructions..."

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +As the tool is **cloud-agnostic**, we are always looking to add more number of **cloud providers** to the [existing list](https://docs.komiser.io/configuration/cloud-providers/aws) and a variety of d
We can change this section "As the tool is cloud-agnostic, we are always looking to add more number of cloud providers to the [existing list](https://docs.komiser.io/configuration/cloud-providers/aws) and a variety of different services/resources." to "Due to the nature of Komiser, a cloud-agnostic cloud management tool, our work is never really done, there are always more providers and cloud services that can be added, updated and cost calculated."

2023-10-04 14:00 UTC, jakepage91 commented on CONTRIBUTING.md
> +#### 2. Adding a new Cloud Service/Resource
Also same the one above (1. Adding a new Cloud Provider) let's make this larger ### 2. Adding a new Cloud Service/Resource

2023-10-05 08:33 UTC, verma-kunal commented on CONTRIBUTING.md
> +> ### Keeping your Fork Up-to-Date
the main reason was to highlight this part actually! because merge conflicts can be confusing especially for beginners, so keeping the fork up to date, before committing new changes is always a good practice and prevents merge conflicts

what do you think?

2023-10-05 08:36 UTC, verma-kunal commented on CONTRIBUTING.md
> +As the tool is **cloud-agnostic**, we are always looking to add more number of **cloud providers** to the [existing list](https://docs.komiser.io/configuration/cloud-providers/aws) and a variety of d
sure!

2023-10-05 08:40 UTC, verma-kunal commented
thanks for the suggestions @jakepage91 ! All resolved ✅

2023-10-05 09:43 UTC, mlabouardy approved these changes

2023-10-05 09:43 UTC, merged

2023-10-06 01:43 UTC, verma-kunal commented
Thanks @mlabouardy :)