Feature/tech 1656
tailwarden/komiser pull request #1043
Opened 2023-10-05 13:38 UTC by Traxmaxx

## Problem

[Provide a brief description of the problem that you are trying to solve with this pull request.]

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-10-10 19:21 UTC, Kolawole99 commented on dashboard/services/settingsService.ts
> +      const res = await fetch(`${BASE_URL}/feedback`, {
Just a quick ask, does this EP already exist on the backend

2023-10-10 19:21 UTC, Kolawole99 approved these changes
LGTM pending the comment I left on the endpoint availability

2023-10-11 06:11 UTC, Azanul commented on dashboard/services/settingsService.ts
> +      const res = await fetch(`${BASE_URL}/feedback`, {
https://github.com/tailwarden/komiser/blob/476b273a97bce35c773f57a9c6a05f9699899e8b/internal/api/v1/endpoints.go#L71

2023-10-11 06:28 UTC, Azanul requested changes
Could you also add comments over the SVGs in feedback widget indicating what they are

2023-10-11 06:28 UTC, Azanul commented on dashboard/components/modal/Modal.stories.tsx
> +        {Story()}
The comment makes partial sense as `Story()` is used. I suggest either fix the comment or drop it altogether.

2023-10-11 08:10 UTC, Traxmaxx commented
> Could you also add comments over the SVGs in feedback widget indicating what they are

I actually plan on moving them into `/icons` in the next steps and then also add all of them to storybook. What do you think? There should be a common place in storybook where contributors can look up all the icons existing already

2023-10-11 12:33 UTC, mlabouardy approved these changes

2023-10-11 12:43 UTC, merged