feat: Fix Cost Calculation for AWS CloudFront Distributions
tailwarden/komiser pull request #1083
Opened 2023-10-11 18:38 UTC by bishal7679

## Problem #877 

Currently cost for AWS cloudfront is full static and showing wrong.
 
## Solution

This PR is fixing that issue by adding more metrics for `lambda-edge-duration`, `lambda-edge-requests`, `function-invocations` with pricemap fetching.

## Changes Made

- Fetching price info using AWS SDK price module using `AmazonCloudFront` service code and appropriate filters.
- getting price map using util function GetPriceMap from [utils.go](https://github.com/tailwarden/komiser/blob/develop/providers/aws/utils/utils.go)
- fetching distribution objects using cloudfront client
- also fetching `lambda-edge-duration`, `lambda-edge-requests`, `function-invocations` metrics using cloudwatch
- Finally added dynamic calculation as per all the metrics

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

Pricingoutput :- 
[pricing.json](https://github.com/tailwarden/komiser/files/12873490/pricing.json)

2023-10-12 02:57 UTC, bishal7679 commented
/cc @AvineshTripathi @Azanul

2023-10-12 04:53 UTC, Azanul requested changes

2023-10-12 04:53 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +}
Can't we convert to GB instead? We do the same by multiplying by 1024 to the result

2023-10-12 04:53 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +			requestsCost := awsUtils.GetCost(priceMap["CloudFront-Requests"], requests/10000)
Where did you get the keys for priceMap?

2023-10-12 04:53 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +			functionInvocationsCost := awsUtils.GetCost(priceMap["AWS-CloudFront-FunctionInvocation"], functionInvocation)
Where did you get this key for priceMap?

2023-10-12 05:03 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +			functionInvocationsCost := awsUtils.GetCost(priceMap["AWS-CloudFront-FunctionInvocation"], functionInvocation)
Yes! updated the code with a function. Searched about it but was not getting the appropriate key. Give your suggestion on the getRate function now

2023-10-12 05:05 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +}
Yes I thought it would be more efficient not to multiply inline

2023-10-12 05:06 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +			requestsCost := awsUtils.GetCost(priceMap["CloudFront-Requests"], requests/10000)
Honestly I asked chatgpt about finding the keys as I was unable to find.

2023-10-12 05:07 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +			requestsCost := awsUtils.GetCost(priceMap["CloudFront-Requests"], requests/10000)
Should we keep it static like previous???

2023-10-12 05:08 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +}
ok i got it

2023-10-12 09:40 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +			requestsCost := awsUtils.GetCost(priceMap["CloudFront-Requests"], requests/10000)
Let me see if I can find the correct keys

2023-10-13 06:12 UTC, bishal7679 commented
@Azanul any update??

2023-10-13 06:37 UTC, Azanul commented
> @Azanul any update??

Yes, I looked into costing of CloudFront. I found out that there are only 3 components to CloudFront cost: CF distributions, CF Functions & CF Origin Shield requests. ref: https://aws.amazon.com/cloudfront/pricing/
Other costs that are being calculated here don't belong here, they belong with their own services such as AWS Lambda.
I'd suggest you look into [what a CloudFront distribution is](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-working-with.html) and their review [it's cost calculation](https://aws.amazon.com/cloudfront/pricing/)

2023-10-13 06:40 UTC, bishal7679 commented
I am including lambda-edge as our pricingoutput is giving those

2023-10-13 06:59 UTC, Azanul commented
> I am including lambda-edge as our pricingoutput is giving those and what the issue with it? if someone use lambda as edge with cloudfront distribution then they will be charged by some amount otherwise it will remain $0 isnt it?

The issue that you're trying to resolve is for CloudFront Distributions, the file that you're making changes to is for CloudFront Distributions not CloudFront Functions or Origin Shield requests.

>if someone use lambda as edge with cloudfront distribution then they will be charged by some amount

That'll be accounted for in it's own resource

2023-10-13 07:05 UTC, Azanul commented
I think the respective issue description is misleading as it says we do not have the calculation whereas the calculation is there. The only thing off about the calculation seems to be the hard-coded prices.
cc: @mlabouardy @AvineshTripathi @ShubhamPalriwala

2023-10-13 07:11 UTC, bishal7679 commented
> I think the respective issue description is misleading as it says we do not have the calculation whereas the calculation is there. The only thing off about the calculation seems to be the hard-coded prices. cc: @mlabouardy @AvineshTripathi @ShubhamPalriwala

Yeah I noticed! So should we include all the charges distribution + function. and resolve with this issue only? Otherwise we have to create different issue for those.
WDYT only distribution charges are enough or adding others with it would make it much more efficient @Azanul @mlabouardy @AvineshTripathi

2023-10-15 05:29 UTC, bishal7679 commented
@jakepage91 Can we add `hold` label for this PR

2023-10-19 19:15 UTC, mlabouardy commented
> @jakepage91 Can we add `hold` label for this PR
Hey @bishal7679 sorry for jumping late to the thread, is there something I can help with to move forward with your PR?

2023-10-20 07:30 UTC, AvineshTripathi commented
@mlabouardy we have intentionally kept this on hold to dicuss the changes on cost calculation to avoid repeatative work!

2023-10-21 17:14 UTC, bishal7679 commented
closing this PR as awsutils recent changes are not being rendered onto my `feature/correct-cost-for-cloudformation` branch locally [PS:- did `git pull` & `sync`]
and raising a new PR

2023-10-21 17:15 UTC, closed without merging