Update Contribution Guidelines
tailwarden/komiser pull request #1087
Opened 2023-10-12 12:14 UTC by Traxmaxx

## Problem

Improve the contribution guidelines with missing informations for frontend development onboarding. Also add links to internal document references and cross-reference the QUickstart Guide for adding a `config.toml`

## Solution

Instruvtions are missing some key steps which is referecnes externally. This PR add the missing steps and cross-reference external documentation for things like setting up the `config.toml`

## Changes Made

- Link references to internal sections
- Fix spelling mistakes
- Add content for missings steps
- Improve the README inside `/dashboard` for frontend specific thigns (TBD)

## How to Test
Read the `.md` files and make sure they parse fine. That's it.

## Screenshots
None needed. Use GitHub Markdown preview

## Notes

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [x] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-10-12 13:19 UTC, jakepage91 reviewed
Just these three comments. Everything thing else looks super great and clean!

2023-10-12 13:19 UTC, jakepage91 commented on dashboard/README.md
> +1. run the development server:
Could we capitalize the "r" here

2023-10-12 13:19 UTC, jakepage91 commented on dashboard/README.md
> +2. open [http://localhost:3002/](http://localhost:3002). If you see the dashboard, congrats! It's all up and running correctly.
Could we capitalize the "o" here

2023-10-12 13:19 UTC, jakepage91 commented on CONTRIBUTING.md
> -> ```
These particular backticks Im guessing should be removed since they are turning the whole section below into a code box. Breaking to format of the actual code.

2023-10-12 13:49 UTC, Kolawole99 requested changes

2023-10-12 13:49 UTC, Kolawole99 commented on CONTRIBUTING.md
> +	git commit -m "nice_commit_description"
I assume the user would not be able to commit this due to commitlint:

`git commit - m "feat(cube-cost): nice commit description"`

We could add the commit lint spec here https://commitlint.js.org/#/concepts-commit-conventions

2023-10-12 15:05 UTC, Traxmaxx commented on CONTRIBUTING.md
> -> ```
should be fixed now!

2023-10-13 09:14 UTC, mlabouardy approved these changes

2023-10-13 09:18 UTC, merged