feat: fetch DynamoDB costs for RCUs and WCUs
tailwarden/komiser pull request #1111
Opened 2023-10-17 10:36 UTC by Traxmaxx

## Problem
We have no costs on DynamoDB resources

## Solution

Fetch costs of DynamoDB resources

## Changes Made

- Extend `aws:dynamodb:tables.go` to fetch RCUs and WCUs through table details
- ...

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-10-18 05:32 UTC, AvineshTripathi commented on providers/aws/dynamodb/tables.go
> +			return resources, err
I dont think we should return this as we still can store the resources irrespective to the cost metrics. What do you think?

2023-10-18 06:03 UTC, AvineshTripathi requested changes

2023-10-18 10:51 UTC, Traxmaxx commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
@AvineshTripathi I moved it into utils and the tests as well. Running them though returns 
```logtalk
--- FAIL: TestGetPriceMap (0.00s)
    --- FAIL: TestGetPriceMap/Test_case_3 (0.00s)
        utils_test.go:208: Expected 0 price dimensions for group , but got 1
FAIL
FAIL	github.com/tailwarden/komiser/providers/aws/utils	0.331s
FAIL
```

What is the actual status of the backend testsuite? It looks like none are run in the pipeline

```logtalk
Run make test
go test -v 
?   	github.com/tailwarden/komiser	[no test files]
```

I'm wondering if I should try to fix the test or just create an issue for it 🤔

2023-10-18 17:50 UTC, AvineshTripathi commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
Good call we should look into this however in some other PR to not keep this waiting. cc @Azanul I think you were refactoring somthing in the PriceMap utils

2023-10-18 18:08 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
I had hardcoded the field in failing test. I guess when I tested, I must have seen the cached test results.

2023-10-18 18:16 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
Regarding backend testsuite & it's CI integration, we have minimal coverage right now but we can run it in CI.
I think aiming for test coverage right now might be premature as many resources are yet to have their cost calculation.

2023-10-18 18:26 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +		if tableDetails != nil && tableDetails.Table != nil && tableDetails.Table.ProvisionedThroughput != nil {
```suggestion
		if tableDetails.Table != nil && tableDetails.Table.ProvisionedThroughput != nil {
```
`tableDetails` won't be nil if there's no error

2023-10-18 18:28 UTC, Traxmaxx commented on providers/aws/dynamodb/tables.go
> +	// https://discord.com/channels/932683789384183808/1117721764957536318/1162338171435090032
Does this mean there could be potentially different prices returned per region? 🤔

2023-10-18 18:29 UTC, Traxmaxx commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
> Regarding backend testsuite & it's CI integration, we have minimal coverage right now but we can run it in CI. I think aiming for test coverage right now might be premature as many resources are yet to have their cost calculation.

I agree but having a working test command running in CI is the first step imho. Test coverage can be built up over a long time afterwards

2023-10-18 18:35 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +	// https://discord.com/channels/932683789384183808/1117721764957536318/1162338171435090032
At the same place they say
>The AWS Region is the API endpoint for the Price List Query API. The endpoints aren't related to product or service attributes.

So, IDTS but it's worth checking out

2023-10-18 18:38 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
I agree, let's get this PR done and raise another for the CI or let me know if you want me to do it.

2023-10-18 19:01 UTC, Azanul requested changes

2023-10-19 05:23 UTC, AvineshTripathi commented on providers/aws/dynamodb/tables.go
> +	// https://discord.com/channels/932683789384183808/1117721764957536318/1162338171435090032
evem the cost explorer gives only one endpoint https://docs.aws.amazon.com/cost-management/latest/userguide/ce-api.html

2023-10-19 09:32 UTC, Traxmaxx commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
So I keethe tests as is and adress the tests situation in a different PR?

2023-10-19 09:34 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +func Int64PtrToFloat64(i *int64) float64 {
yes

2023-10-19 13:34 UTC, Traxmaxx commented on providers/aws/dynamodb/tables.go
> +	// https://discord.com/channels/932683789384183808/1117721764957536318/1162338171435090032
I talked with @mlabouardy and I will create a helper to take care of this in a new PR in the next days.

2023-10-19 13:55 UTC, Azanul commented on providers/aws/dynamodb/tables.go
> +	// https://discord.com/channels/932683789384183808/1117721764957536318/1162338171435090032
I don't think it's worth fixing as the refactor work @AvineshTripathi is doing will probably address this as well. Since the client will be created only once.

2023-10-19 16:18 UTC, Azanul approved these changes

2023-10-19 19:06 UTC, mlabouardy approved these changes

2023-10-19 19:09 UTC, merged