(feature/0457-support-amazon-cloudfront-function): Support Amazon Clo…
tailwarden/komiser pull request #1127
Opened 2023-10-22 12:56 UTC by jolo-dev

Collect Amazon CloudFront function

## Solution

Add to Cloudfront Functions a new file `functions.go`

## Changes Made

- new file `provider/aws/cloudfront/functions.go`

## How to Test

Create a new Cloudfront functions: https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/functions/create

## Screenshots

![Screenshot 2023-10-22 at 14 45 32](https://github.com/tailwarden/komiser/assets/54506108/90dc1b24-361d-4943-974f-629c32884a3c)

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [X] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [X] Changes have been thoroughly tested
- [X] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [X] Any dependencies have been added to the project, if necessary

## Reviewers

2023-10-23 09:18 UTC, Traxmaxx commented on providers/aws/cloudfront/functions.go
> +	client.AWSClient.Region = tempRegion
🙌

2023-10-23 09:34 UTC, jolo-dev commented
@Traxmaxx the dashboard fails because of the missing Toast component: https://discord.com/channels/932683789384183808/933353577102061669/1165250794417836072

2023-10-23 09:40 UTC, Traxmaxx commented
> @Traxmaxx the dashboard fails because of the missing Toast component: https://discord.com/channels/932683789384183808/933353577102061669/1165250794417836072

Hey thanks! I'm aware and try to get someone from the maintainers to help me review open PRs to get the fix in asap!

2023-10-24 12:28 UTC, mlabouardy approved these changes

2023-10-25 13:49 UTC, bishal7679 commented
@mlabouardy This changes has already been raised by this PR #1131
and had to close it due to checks failing!

2023-10-25 14:04 UTC, AvineshTripathi commented
Hey @bishal7679 your PR also adds something some details to distributions, I would recommend you to review this PR to see if it matches to what your changes are and we can remove those from your PR. However we will make sure you get added as a collaborator for this PR.

This is just to make sure both get credits for the amazing work, however i can only do that when both you and @jolo-dev are ready for it. Thanks!

2023-10-25 18:18 UTC, bishal7679 commented
> Hey @bishal7679 your PR also adds something some details to distributions, I would recommend you to review this PR to see if it matches to what your changes are and we can remove those from your PR. However we will make sure you get added as a collaborator for this PR.
> 
> This is just to make sure both get credits for the amazing work, however i can only do that when both you and @jolo-dev are ready for it. Thanks!

@AvineshTripathi I completely support this! Wouldn't it be good?? get PR #1131 merged first [PS:- might get complicated for merge conflict] after then this PR #1127 could be addon since both are adding same file `functions.go` and in #1131 dynamic pricing and more metrics being used and #1127 its invocation metric can be added there to make the calculation more efficient??

2023-10-25 20:26 UTC, jolo-dev commented
@AvineshTripathi I believe the one of #1131  is a bit more sophisticated. However, there might be a few changes needed. He got the Duration which I couldn't find. @bishal7679 Have you tried and that worked?
L138 and L158.
And I am not sure about the Namespace of L92.

2023-10-25 20:29 UTC, AvineshTripathi commented
Great! I keep this to you'll and let me know how you want to proceed or need any assitance.

2023-10-28 15:03 UTC, bishal7679 requested changes
Hope it helps!
REF :- [metricname](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/programming-cloudwatch-metrics.html#cloudfront-metrics-function-values)

2023-10-29 04:50 UTC, Azanul requested changes

2023-10-29 04:50 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +			monthlyCost := invocations * 0.0000001
```suggestion
			monthlyCost := invocations * costPerInvocation
```

2023-10-29 04:50 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +	freeTierInvocations = 2000000
```suggestion
	freeTierInvocations = 2000000
	costPerInvocation = 0.0000001
```

2023-10-29 09:21 UTC, Azanul approved these changes

2023-10-29 16:20 UTC, bishal7679 approved these changes
LGTM!

2023-10-30 14:12 UTC, merged