Added gh action for hacktoberfest comment
tailwarden/komiser pull request #1130
Opened 2023-10-23 16:26 UTC by AvineshTripathi

2023-10-27 09:15 UTC, mlabouardy requested changes

2023-10-27 09:15 UTC, mlabouardy commented on .github/workflows/hacktoberfest-comments.yaml
> +            ![Image](assets/gh/image.png)
@AvineshTripathi the image is missing, no?

2023-10-27 10:58 UTC, AvineshTripathi commented on .github/workflows/hacktoberfest-comments.yaml
> +            ![Image](assets/gh/image.png)
yep, I couldn't find it so! Also now do you think it is needed? we can create a custom label for crucial prs and give them badges

2023-10-30 14:15 UTC, mlabouardy commented on .github/workflows/hacktoberfest-comments.yaml
> +            ![Image](assets/gh/image.png)
here's the image:
![Hacktoberfest badge](https://github.com/tailwarden/komiser/assets/10320205/6e43001b-27dd-4dac-ba5f-b4bb2f9e0a31)
can you add it to the PR @AvineshTripathi

2023-10-31 13:37 UTC, AvineshTripathi commented on .github/workflows/hacktoberfest-comments.yaml
> +            ![Image](assets/gh/image.png)
where should we keep it? path

2023-10-31 14:33 UTC, closed without merging