feat: Fix Cost Calculation for AWS CloudFront Distributions & Functions
tailwarden/komiser pull request #1131
Opened 2023-10-23 17:13 UTC by bishal7679

## Problem #877 

Currently, cost for AWS CloudFront is full static and showing wrong.
 
## Solution

This PR is fixing that issue by adding more metrics for `lambda-edge-duration`, `lambda-edge-requests`, `origin-shield-request` with pricemap fetching.

## Changes Made

- Fetching price info using AWS SDK price module using `AmazonCloudFront` service code and appropriate filters.
- getting price map using util function GetPriceMap from [utils.go](https://github.com/tailwarden/komiser/blob/develop/providers/aws/utils/utils.go)
- fetching distribution objects & function objects using CloudFront client
- also fetching `lambda-edge-duration`, `lambda-edge-requests`, `origin-shield-request` metrics using CloudWatch
- Finally added dynamic calculation as per all the metrics

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

Pricingoutput :- 
[pricing.json](https://github.com/tailwarden/komiser/files/12873490/pricing.json)

REF :- #1083

2023-10-23 17:25 UTC, bishal7679 commented
@AvineshTripathi @Azanul
PHAL!
Now all checks passed :+1:

2023-10-23 18:44 UTC, AvineshTripathi commented on providers/aws/cloudfront/functions.go
> +		return resources, err
donot return for pricing clients err unless they are panic

2023-10-23 18:51 UTC, bishal7679 commented on providers/aws/cloudfront/functions.go
> +		return resources, err
okay then 
removing the return for only pricing client or for some others as well??

2023-10-24 04:23 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +	pricingClient := pricing.NewFromConfig(*client.AWSClient)
```suggestion
	client.AWSClient.Region = "us-east-1"
	cloudwatchClient := cloudwatch.NewFromConfig(*client.AWSClient)
	pricingClient := pricing.NewFromConfig(*client.AWSClient)
	client.AWSClient.Region = tempRegion
```

2023-10-24 05:16 UTC, Azanul requested changes
The priceMap keys are incorrect, please fix those. Log the pricing output to find the correct keys.

Cloudfront distribution cost is `Data transfer out cost` + `request cost`
Check out the pricing examples in https://aws.amazon.com/cloudfront/pricing/

2023-10-24 05:16 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +	pricingClient := pricing.NewFromConfig(*client.AWSClient)
```suggestion
	pricingClient := pricing.NewFromConfig(*client.AWSClient)
	client.AWSClient.Region = tempRegion
```

2023-10-24 05:20 UTC, bishal7679 commented
> The priceMap keys are incorrect, please fix those. Log the pricing output to find the correct keys.
> 
> Cloudfront distribution cost is `Data transfer out cost` + `request cost` Check out the pricing examples in https://aws.amazon.com/cloudfront/pricing/

But I didn't change anything on this. It was included cost = upload + download + request

2023-10-24 06:15 UTC, AvineshTripathi commented on providers/aws/cloudfront/functions.go
> +		return resources, err
I would say only return if the core ouutput that is function list is throwing error, price calculation, stats etc are things that are addons

2023-10-24 08:10 UTC, Kolawole99 requested changes

2023-10-24 08:10 UTC, Kolawole99 commented on providers/aws/cloudfront/functions.go
> +			lambdaEdgeRequestsCost := awsUtils.GetCost(priceMap["AWS-Lambda-Edge-Requests"], lambdaEdgeRequests/10000000)
I think you should declare a constant for `10000000` this should be descriptive so other developers would have an idea of what this calculation achieves.

2023-10-24 08:42 UTC, Azanul commented
> But I didn't change anything on this. It was included cost = upload + download + request Also help me to get the correct keys. I am unable to find bcoz pricing output doesn't fetch those

Try without the region code filter since for cloudfront from which region the data is fetched is also considered. Here's the full pricing output w/o region code filter.
[op.json](https://github.com/tailwarden/komiser/files/13112457/op.json)

2023-10-24 14:09 UTC, bishal7679 commented
@Azanul @AvineshTripathi PTAL now!

2023-10-24 15:31 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +	pricingClient := pricing.NewFromConfig(*client.AWSClient)
@bishal7679

2023-10-24 15:41 UTC, Azanul requested changes
Cloufroint functions looks good to go from me.

Calculation for distributions requires much more calculation as the implementation here would simply take the last value that parser gets in the list of prices. In short, the location needs to be taken into consideration.

2023-10-24 15:44 UTC, bishal7679 commented
> Cloufroint functions looks good to go from me.
> 
> Calculation for distributions requires much more calculation as the implementation here would simply take the last value that parser gets in the list of prices. In short, the location needs to be taken into consideration.

Could you pls elaborate more
Location what do you mean and do I have to write another metric??

2023-10-24 17:56 UTC, Azanul commented
> > Calculation for distributions requires much more calculation as the implementation here would simply take the last value that parser gets in the list of prices. In short, the location needs to be taken into consideration.
> 
> Could you pls elaborate more Location what do you mean and do I have to write another metric??

If you see the pricing output or the cloudfront pricing page, you'll notice that price is location wise. The location is (probably) from location, the location/region of the origin from the data is fetched. To get this I think we'll probably have to map the aws regions to the listed cloudfront regions and calculate accordingly. Someone with more AWS expertise might be able to confirm.
cc: @mlabouardy @jakepage91

2023-10-25 20:30 UTC, jolo-dev commented on providers/aws/cloudfront/functions.go
> +				Namespace:  aws.String("AWS/LambdaEdge"),
Is that not `aws.String("AWS/Cloudfront")`?

2023-10-25 20:30 UTC, jolo-dev commented on providers/aws/cloudfront/functions.go
> +				Namespace:  aws.String("AWS/LambdaEdge"),
Isn't it `AWS/Cloudfront`?

2023-10-25 20:30 UTC, jolo-dev commented on providers/aws/cloudfront/functions.go
> +				MetricName: aws.String("Duration"),
Does that work? If yes, that would be great 👍

2023-10-25 20:30 UTC, jolo-dev commented on providers/aws/cloudfront/functions.go
> +				Service:    "CloudFront",
Shouldn't it be `Cloudfront Functions`?

2023-10-25 20:30 UTC, jolo-dev commented on providers/aws/cloudfront/functions.go
> +		"service":   "CloudFront",
Shouldn't it be `Cloudfront Functions`?

2023-10-26 00:06 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +				Service:    "CloudFront",
Cloudfront functions isn't a service, it's a resource/sub-resource of Cloudfront service

2023-10-26 09:00 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +				Namespace:  aws.String("AWS/LambdaEdge"),
`AWS/CloudFront`
ref: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/programming-cloudwatch-metrics.html#cloudfront-metrics-global-values

2023-10-26 09:00 UTC, Azanul commented on providers/aws/cloudfront/functions.go
> +				Namespace:  aws.String("AWS/LambdaEdge"),
capital F

2023-10-26 09:44 UTC, Azanul commented
@bishal7679 I recently uncovered an oversight here. Cloudfront functions and Lambda edge functions are different, the current PR mixes them both. I'm looking for the Lambda edge metrics API, when found, we could use those metrics instead of cloudfront function invocations, change the file name and it'll work out.
Cloudfront functions won't need a pricing client either since the price is static globally.

2023-10-26 09:57 UTC, jolo-dev commented on providers/aws/cloudfront/functions.go
> +				Service:    "CloudFront",
You're right.

2023-10-26 09:59 UTC, bishal7679 commented
> @bishal7679 I recently uncovered an oversight here. Cloudfront functions and Lambda edge functions are different, the current PR mixes them both. I'm looking for the Lambda edge metrics API, when found, we could use those metrics instead of cloudfront function invocations, change the file name and it'll work out. Cloudfront functions won't need a pricing client either since the price is static globally.

Found Lambda@Edge is similar to cloudfront means the functions running on cloudfront edge regionally. Thats might be the reason pricing output is giving Lambda edge results for CloudFront

2023-10-26 10:20 UTC, Azanul commented
> Found Lambda@Edge is similar to cloudfront means the functions running on cloudfront edge regionally. Thats might be the reason pricing output is giving Lambda edge results for CloudFront

Lambda edge is a feature of cloudfront only but is different from cloudfront functions

2023-10-27 16:27 UTC, jolo-dev commented
> > > Found Lambda@Edge is similar to cloudfront means the functions running on cloudfront edge regionally. Thats might be the reason pricing output is giving Lambda edge results for CloudFront
> > 
> > 
> > Lambda edge is a feature of cloudfront only but is different from cloudfront functions
> 
> I agree, Lambda@Edge is just a Lambda function that's triggered on a CloudFront edge

So meaning my PR #1127 is not completely useless? :D

2023-10-27 17:41 UTC, bishal7679 commented
> > > > Found Lambda@Edge is similar to cloudfront means the functions running on cloudfront edge regionally. Thats might be the reason pricing output is giving Lambda edge results for CloudFront
> > > 
> > > 
> > > Lambda edge is a feature of cloudfront only but is different from cloudfront functions
> > 
> > 
> > I agree, Lambda@Edge is just a Lambda function that's triggered on a CloudFront edge
> 
> So meaning my PR #1127 is not completely useless? :D

How it'd be useless??
@Azanul @AvineshTripathi What to do with #1131 as its getting long convo

2023-10-27 19:08 UTC, Azanul commented
@bishal7679 @jolo-dev 
- As far as functions part is concerned, let's go ahead with #1127 
- Let's rename the functions file in this PR to lambdaedge, since that's what the calculations here are doing. Recheck metric names again and any respective log or name changes. For now, let's just assume that the cloudwatch metrics api lists cloudfront functions and lambda edges together.
- for distributions, check out [my previous comment](https://github.com/tailwarden/komiser/pull/1131#issuecomment-1777744210).

cc: @AvineshTripathi @mlabouardy

2023-10-29 18:01 UTC, bishal7679 commented
@Azanul How to get appropriate location of any CF dist?
 
- First of all we have to get the edge location of any data transfer out origin REF:- [check](https://aws.amazon.com/cloudfront/features/?whats-new-cloudfront.sort-by=item.additionalFields.postDateTime&whats-new-cloudfront.sort-order=desc])
(bit confused here ...... How to get it as you told `we'll probably have to map the aws regions to the listed cloudfront regions and calculate accordingly`))
- after getting the location we can match that location with pricingoutput `fromLocation` key value. For this we have to use GetPricemap for two field together `transferType` & `fromLocation`



Could you pls check this func I wrote once whether its returning any location getCloudFrontDistributionLocation??
PS :- Tried with IAM and domainName also for getting edge location but no result :(

2023-10-30 05:55 UTC, Azanul commented
> @Azanul How to get appropriate location of any CF dist?
> 
> * First of all we have to get the edge location of any data transfer out origin REF:- [check](https://aws.amazon.com/cloudfront/features/?whats-new-cloudfront.sort-by=item.additionalFields.postDateTime&whats-new-cloudfront.sort-order=desc%5D)
>   (bit confused here ...... How to get it as you told `we'll probably have to map the aws regions to the listed cloudfront regions and calculate accordingly`))

Since we fetch all resources one region at a time, we can map them to the pricing regions of CF. Like `us-east-1` maps to `United States, Mexico, and Canada` and `ap-south-1` maps to `India`.

2023-10-30 06:31 UTC, Azanul commented
> * after getting the location we can match that location with pricingoutput `fromLocation` key value. For this we have to use GetPricemap for two field together `transferType` & `fromLocation`

I think you can write a manual function for this

> Could you pls check this func I wrote once whether its returning any location getCloudFrontDistributionLocation??
> 

Check my previous comment. https://github.com/tailwarden/komiser/pull/1131#issuecomment-1784529525

2023-10-30 07:01 UTC, bishal7679 commented
> > @Azanul How to get appropriate location of any CF dist?
> > 
> > * First of all we have to get the edge location of any data transfer out origin REF:- [check](https://aws.amazon.com/cloudfront/features/?whats-new-cloudfront.sort-by=item.additionalFields.postDateTime&whats-new-cloudfront.sort-order=desc%5D)
> >   (bit confused here ...... How to get it as you told `we'll probably have to map the aws regions to the listed cloudfront regions and calculate accordingly`))
> 
> Since we fetch all resources one region at a time, we can map them to the pricing regions of CF. Like `us-east-1` maps to `United States, Mexico, and Canada` and `ap-south-1` maps to `India`

we can map those location with a region
but problem is how to know which distribution is from which location India or japan??

2023-10-30 07:13 UTC, Azanul commented
> we can map those location with a region but problem is how to know which distribution is from which location India or japan??

You can find the region (`us-east-1` or `ap-east-1`) from the aws client config. Write a static map to map it to the respective pricing region.

2023-10-30 17:56 UTC, bishal7679 commented
@Azanul Now its mapped with location and rather than going through unnecessary all edge location for one region, if one edge location is matched then taking its price as all edge locations price are same for one region

2023-10-30 18:58 UTC, Azanul requested changes
I don't think we need to iterate through all the regions every time, we'd need to map only the current region from aws client to the region CF classification.

Let's kill the clutter and take one step at a time. Let's drop the changes in CF distributions till someone has more bandwidth to test it out and check whether our assumptions are correct or not. Instead, let's focus on lambdaedge, it has less room for error.

2023-10-30 18:58 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +}
Why is this a `map[string][]string` instead of `map[string]string`?
Also, I don't think it's correct either, check available zones in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

2023-10-30 18:58 UTC, Azanul commented on providers/aws/cloudfront/lambdaedge.go
> +	pricingClient := pricing.NewFromConfig(*client.AWSClient)
```suggestion
	pricingClient := pricing.NewFromConfig(*client.AWSClient)
	client.AWSClient.Region = tempRegion
```

2023-10-30 19:25 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +}
Its map[string][]string
So that its not get a long list of every single edge locations when its covering under one region
And I cross checked the regions with locations from aws account zones. They are correct almost

2023-10-30 19:29 UTC, bishal7679 commented
> I don't think we need to iterate through all the regions every time, we'd need to map only the current region from aws client to the region CF classification.
> 
> Let's kill the clutter and take one step at a time. Let's drop the changes in CF distributions till someone has more bandwidth to test it out and check whether our assumptions are correct or not. Instead, let's focus on lambdaedge, it has less room for error.

If you see carefully the region, location loop is not iterating every time
Its iterating one region and under that region if only one edge location is matched then it will break the loop and fetch the unit price and again go to another region
And you suggested this above comment
`Since we fetch all resources one region at a time, we can map them to the pricing regions`

2023-10-30 19:32 UTC, bishal7679 commented
According the logic which I put I hope it should work properly with location 
And its simple

2023-10-30 19:33 UTC, bishal7679 commented
> According the logic which I put I hope it should work properly with location And its simple

@jolo-dev @AvineshTripathi @Kolawole99 would anyone mind to test this code once whether its fetching properly

2023-10-30 23:43 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +}
The CF regions are strings, I don't understand the mapping to []string.
How would you handle "eu-west-3" region?

2023-10-30 23:49 UTC, Azanul commented
> > I don't think we need to iterate through all the regions every time, we'd need to map only the current region from aws client to the region CF classification.
> > Let's kill the clutter and take one step at a time. Let's drop the changes in CF distributions till someone has more bandwidth to test it out and check whether our assumptions are correct or not. Instead, let's focus on lambdaedge, it has less room for error.
> 
> If you see carefully the region, location loop is not iterating every time Its iterating one region and under that region if only one edge location is matched then it will break the loop and fetch the unit price and again go to another region And you suggested this above comment `Since we fetch all resources one region at a time, we can map them to the pricing regions`

The location loop is the anti-pattern here. Regions are not handled in every service's file, they're handled in provider's file i.e., aws in this case.

2023-10-31 04:15 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +}
eu-west-3 regions corresponding edge location is not present in pricing output

2023-10-31 04:20 UTC, Azanul commented on providers/aws/cloudfront/distributions.go
> +}
I think the pricing output is page 1, the response from pricing client is always paginated.

2023-10-31 04:34 UTC, bishal7679 commented
> > > I don't think we need to iterate through all the regions every time, we'd need to map only the current region from aws client to the region CF classification.
> > > Let's kill the clutter and take one step at a time. Let's drop the changes in CF distributions till someone has more bandwidth to test it out and check whether our assumptions are correct or not. Instead, let's focus on lambdaedge, it has less room for error.
> > 
> > 
> > If you see carefully the region, location loop is not iterating every time Its iterating one region and under that region if only one edge location is matched then it will break the loop and fetch the unit price and again go to another region And you suggested this above comment `Since we fetch all resources one region at a time, we can map them to the pricing regions`
> 
> The location loop is the anti-pattern here. Regions are not handled in every service's file, they're handled in provider's file i.e., aws in this case.

since all corresponding edge location of every region of `aws.go` getRegion func is not present in pricing output how to map all as map[string]string???
Then it'd not be possible to take the region from aws.go thats why it is taken in the service file itself

2023-10-31 04:44 UTC, Azanul commented
> > > If you see carefully the region, location loop is not iterating every time Its iterating one region and under that region if only one edge location is matched then it will break the loop and fetch the unit price and again go to another region And you suggested this above comment `Since we fetch all resources one region at a time, we can map them to the pricing regions`
> > 
> > 
> > The location loop is the anti-pattern here. Regions are not handled in every service's file, they're handled in provider's file i.e., aws in this case.
> 
> since all corresponding edge location of every region of `aws.go` getRegion func is not present in pricing output how to map all as map[string]string??? Then it'd not be possible to take the region from aws.go thats why it is taken in the service file itself

try to increase max results for the pricing output

2023-10-31 04:52 UTC, bishal7679 commented
> > > > If you see carefully the region, location loop is not iterating every time Its iterating one region and under that region if only one edge location is matched then it will break the loop and fetch the unit price and again go to another region And you suggested this above comment `Since we fetch all resources one region at a time, we can map them to the pricing regions`
> > > 
> > > 
> > > The location loop is the anti-pattern here. Regions are not handled in every service's file, they're handled in provider's file i.e., aws in this case.
> > 
> > 
> > since all corresponding edge location of every region of `aws.go` getRegion func is not present in pricing output how to map all as map[string]string??? Then it'd not be possible to take the region from aws.go thats why it is taken in the service file itself
> 
> try to increase max results for the pricing output

Could you try once either? I've removed all the attribute only using serviceCode.

2023-10-31 05:16 UTC, Azanul commented
> > > since all corresponding edge location of every region of `aws.go` getRegion func is not present in pricing output how to map all as map[string]string??? Then it'd not be possible to take the region from aws.go thats why it is taken in the service file itself
> > 
> > 
> > try to increase max results for the pricing output
> 
> Could you try once either? I've removed all the attribute only using serviceCode.

When setting MaxResults to 100
[op.json](https://github.com/tailwarden/komiser/files/13212250/op.json)

2023-10-31 05:17 UTC, bishal7679 commented
> > > > since all corresponding edge location of every region of `aws.go` getRegion func is not present in pricing output how to map all as map[string]string??? Then it'd not be possible to take the region from aws.go thats why it is taken in the service file itself
> > > 
> > > 
> > > try to increase max results for the pricing output
> > 
> > 
> > Could you try once either? I've removed all the attribute only using serviceCode.
> 
> When setting MaxResults to 100 [op.json](https://github.com/tailwarden/komiser/files/13212250/op.json)

I've taken all the results from your given op.json previously :smiley:

2023-10-31 05:35 UTC, Azanul commented
> > > Could you try once either? I've removed all the attribute only using serviceCode.
> > 
> > 
> > When setting MaxResults to 100 [op.json](https://github.com/tailwarden/komiser/files/13212250/op.json)
> 
> I've taken all the results from your given op.json previously 😃

This is what you get when printing the full paginated result
[op.json](https://github.com/tailwarden/komiser/files/13212425/op.json)

2023-10-31 07:37 UTC, bishal7679 commented
> > > > Could you try once either? I've removed all the attribute only using serviceCode.
> > > 
> > > 
> > > When setting MaxResults to 100 [op.json](https://github.com/tailwarden/komiser/files/13212250/op.json)
> > 
> > 
> > I've taken all the results from your given op.json previously 😃
> 
> This is what you get when printing the full paginated result [op.json](https://github.com/tailwarden/komiser/files/13212425/op.json)

OK! It is giving 2 extra region. suggest modification in my full distribution code and in the location code as well. Would be happy to apply `commit suggestion` and get this PR ready to merge!

2023-10-31 08:05 UTC, Azanul commented
> > > I've taken all the results from your given op.json previously 😃
> > 
> > 
> > This is what you get when printing the full paginated result [op.json](https://github.com/tailwarden/komiser/files/13212425/op.json)
> 
> OK! It is giving 2 extra region. suggest modification in my full distribution code and in the location code as well. Would be happy to apply `commit suggestion` and get this PR ready to merge!

https://github.com/tailwarden/komiser/pull/1131#issuecomment-1786219858
It is certainly possible

2023-10-31 18:31 UTC, bishal7679 commented
@Azanul Now everything is working nicely! 
- All region is being taken from provider aws.go and being matched with the map I created and fething the unit price
Now only let me know how you got this [op.json](https://github.com/tailwarden/komiser/pull/1131#issuecomment-1786479347)

```go
pricingOutput, err := pricingClient.GetProducts(ctx, &pricing.GetProductsInput{
		ServiceCode: aws.String("AmazonCloudFront"),
	})
```
will only by ServiceCode work or need to add another attributes?

2023-11-01 15:23 UTC, bishal7679 commented
PTAL!
/cc @Azanul @mlabouardy @AvineshTripathi
@jakepage91

2023-11-01 16:02 UTC, Kolawole99 requested changes

2023-11-01 16:02 UTC, Kolawole99 commented on providers/aws/cloudfront/distributions.go
> +func getRegionMapping() map[string]string {
I think it will be better to have this region mapping in an AWS util file so it can be reused by any AWS service needing to map regions.

Also, we should cross-verify if this does not exist (or in a different format) in the codebase as of now

2023-11-01 16:09 UTC, bishal7679 commented on providers/aws/cloudfront/distributions.go
> +func getRegionMapping() map[string]string {
Yeap you are right but this mapping is cloudfront specific
I'm not sure same edge location will be needed for any other service and same edge locations might not be present in their pricingoutput
WDYT??

2023-11-02 11:53 UTC, Azanul commented
>   Now only let me know how you got this [op.json](https://github.com/tailwarden/komiser/pull/1131#issuecomment-1786479347) max result
> 
> ```go
> pricingOutput, err := pricingClient.GetProducts(ctx, &pricing.GetProductsInput{
> 		ServiceCode: aws.String("AmazonCloudFront"),
> 	})
> ```
> 
> will only by ServiceCode work or need to add another attributes?

The result is paginated anyway, so I looped through all the pages (used NextToken) and merged the results into one.

2023-11-02 13:54 UTC, bishal7679 commented
> > Now only let me know how you got this [op.json](https://github.com/tailwarden/komiser/pull/1131#issuecomment-1786479347) max result
> > ```go
> > pricingOutput, err := pricingClient.GetProducts(ctx, &pricing.GetProductsInput{
> > 		ServiceCode: aws.String("AmazonCloudFront"),
> > 	})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > will only by ServiceCode work or need to add another attributes?
> 
> The result is paginated anyway, so I looped through all the pages (used NextToken) and merged the results into one.

Yeah! I see
What to do then??

2023-11-02 15:26 UTC, Azanul commented
> Yeah! I see What to do then??

Let's use upcoming Komiser weekly to have an exhaustive discussion on AWS Cloudfront and our approach for calculating it's cost.

cc: @mlabouardy @jakepage91

2023-11-06 15:06 UTC, bishal7679 commented
@Azanul what's the update on it

2023-11-08 15:36 UTC, Azanul commented
> @Azanul what's the update on it

Will soon give an update on this, we might pivot from our current cost approach for AWS support

2023-11-16 05:20 UTC, Azanul commented
@bishal7679 We're going to go with cost explorer API integration. It's safe to close this PR

2023-11-16 06:13 UTC, bishal7679 commented
> @bishal7679 We're going to go with cost explorer API integration. It's safe to close this PR

Its been three times closing same PR after a lot of consuming time
But no issue 😐
get it done by cost explorer 👍

2023-11-16 06:13 UTC, closed without merging

2023-11-16 06:16 UTC, Azanul commented
> > @bishal7679 We're going to go with cost explorer API integration. It's safe to close this PR
> 
> Its been three times closing same PR after a lot of consuming time But no issue 😐 get it done by cost explorer 👍

Another day in a software developer's life