feat: calculate cost of Kinesis Data Streams using provisioned mode
tailwarden/komiser pull request #1137
Opened 2023-10-24 20:07 UTC by jbleduigou

## Problem

Add the cost calculation for Kinesis Data Streams using provisioned mode.

## Solution

We first need to retrieve the prices by using the pricing API of AWS.
Then we have two parts in the cost : a cost per shard and then a cost depending on the number of events ingested by the stream.

## Changes Made

- Added the cost calculation logic in `providers/aws/kinesis/streams.go`
- Added unit tests accordingly in `providers/aws/kinesis/streams_test.go`
- Added two mocks to support the unit tests in `mocks/cloudwatch.go` and `mocks/pricing.go`

## How to Test

You will need to create a Kinesis Data Steam in the AWS Console.
You might need to wait a few hours before the cost calculation start to kick in.

## Screenshots

![image](https://github.com/tailwarden/komiser/assets/1489214/173e14a5-321e-4f78-a3b2-f02e8ffd9691)

## Notes

n/a

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [x] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@mlabouardy

2023-10-25 14:41 UTC, Azanul requested changes
Could you also attach the pricing output received, I'd like to check the price map keys

2023-10-25 19:29 UTC, jbleduigou commented
Here is the pricing:
```json
{
    "PriceList": [
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"servicecode\":\"AmazonKinesis\",\"groupDescription\":\"Number of GBs of data retrieved by consumers using enhanced fan-out\",\"usagetype\":\"ReadBytes\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"EnhancedFanoutDataRetrieval\",\"group\":\"Enhanced fan-out GB of data retrieved\"},\"sku\":\"4V6WBV2SGNWG4M9M\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"4V6WBV2SGNWG4M9M.JRTCKXETXF\":{\"priceDimensions\":{\"4V6WBV2SGNWG4M9M.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB\",\"endRange\":\"Inf\",\"description\":\"$0.013 per GB of data retrieved by consumers using enhanced fan-out\",\"appliesTo\":[],\"rateCode\":\"4V6WBV2SGNWG4M9M.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0130000000\"}}},\"sku\":\"4V6WBV2SGNWG4M9M\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"servicecode\":\"AmazonKinesis\",\"usagetype\":\"OnDemand-ExtendedRetention-ByteHrs\",\"description\":\"per byte hour data stored within 1-7 days\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"OnDemandExtendedRetentionByteHrs\",\"group\":\"OnDemand\"},\"sku\":\"59DG9NNVUBGN3C5M\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"59DG9NNVUBGN3C5M.JRTCKXETXF\":{\"priceDimensions\":{\"59DG9NNVUBGN3C5M.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB-month\",\"endRange\":\"Inf\",\"description\":\"0.10 per GB-month for retention within 1-7 days\",\"appliesTo\":[],\"rateCode\":\"59DG9NNVUBGN3C5M.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.1000000000\"}}},\"sku\":\"59DG9NNVUBGN3C5M\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"servicecode\":\"AmazonKinesis\",\"usagetype\":\"OnDemand-BilledOutgoingEFOBytes\",\"description\":\"Per GB of data retrieved by consumers using enhanced fan-out\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"OnDemandEFODataRetrieval\",\"group\":\"OnDemand\"},\"sku\":\"5KE89N55PB48GC9E\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"5KE89N55PB48GC9E.JRTCKXETXF\":{\"priceDimensions\":{\"5KE89N55PB48GC9E.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB\",\"endRange\":\"Inf\",\"description\":\"0.05 per GB of data read using EFO Consumer\",\"appliesTo\":[],\"rateCode\":\"5KE89N55PB48GC9E.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0500000000\"}}},\"sku\":\"5KE89N55PB48GC9E\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"maximumExtendedStorage\":\"7 days\",\"servicecode\":\"AmazonKinesis\",\"groupDescription\":\"Number of standard shard hours\",\"usagetype\":\"Storage-ShardHour\",\"standardStorageRetentionIncluded\":\"1 day\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"shardHourStorage\",\"group\":\"Provisioned shard hour\"},\"sku\":\"7RXVY4V5SG8NQC38\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"7RXVY4V5SG8NQC38.JRTCKXETXF\":{\"priceDimensions\":{\"7RXVY4V5SG8NQC38.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"ShardHour\",\"endRange\":\"Inf\",\"description\":\"$0.015 per provisioned shard-hour\",\"appliesTo\":[],\"rateCode\":\"7RXVY4V5SG8NQC38.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0150000000\"}}},\"sku\":\"7RXVY4V5SG8NQC38\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"servicecode\":\"AmazonKinesis\",\"usagetype\":\"OnDemand-BilledIncomingBytes\",\"description\":\"Per GB of data ingested\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"OnDemandDataIngested\",\"group\":\"OnDemand\"},\"sku\":\"826E7FJQWVKN3CBH\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"826E7FJQWVKN3CBH.JRTCKXETXF\":{\"priceDimensions\":{\"826E7FJQWVKN3CBH.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB\",\"endRange\":\"Inf\",\"description\":\"0.08 per GB of data written\",\"appliesTo\":[],\"rateCode\":\"826E7FJQWVKN3CBH.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0800000000\"}}},\"sku\":\"826E7FJQWVKN3CBH\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"maximumExtendedStorage\":\"7 days\",\"servicecode\":\"AmazonKinesis\",\"groupDescription\":\"Number of extended shard hours\",\"usagetype\":\"Extended-ShardHour\",\"standardStorageRetentionIncluded\":\"1 day\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"shardHourStorage\",\"group\":\"Addon shard hour\"},\"sku\":\"9DT967X6YQX3AYMB\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"9DT967X6YQX3AYMB.JRTCKXETXF\":{\"priceDimensions\":{\"9DT967X6YQX3AYMB.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"ShardHour\",\"endRange\":\"Inf\",\"description\":\"$0.020 per extended shard-hour\",\"appliesTo\":[],\"rateCode\":\"9DT967X6YQX3AYMB.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0200000000\"}}},\"sku\":\"9DT967X6YQX3AYMB\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"maximumExtendedStorage\":\"365 Days\",\"servicecode\":\"AmazonKinesis\",\"groupDescription\":\"Number of GB-month long-term data storage\",\"usagetype\":\"LongTermRetention-ByteHrs\",\"standardStorageRetentionIncluded\":\"1 day\",\"locationType\":\"AWS Region\",\"location\":\"US East (N. Virginia)\",\"servicename\":\"Amazon Kinesis\",\"operation\":\"LongTermRetentionByteHrs\",\"group\":\"Long-term Data Retention GB-month\"},\"sku\":\"ECQFCZZ6DTWE83YB\"},\"serviceCode\":\"AmazonKinesis\",\"terms\":{\"OnDemand\":{\"ECQFCZZ6DTWE83YB.JRTCKXETXF\":{\"priceDimensions\":{\"ECQFCZZ6DTWE83YB.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB-month\",\"endRange\":\"Inf\",\"description\":\"$0.023 per GB-month for Long-term data storage (data older than 7 days) in US East (N. Virginia)\",\"appliesTo\":[],\"rateCode\":\"ECQFCZZ6DTWE83YB.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0230000000\"}}},\"sku\":\"ECQFCZZ6DTWE83YB\",\"effectiveDate\":\"2023-06-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20230801012600\",\"publicationDate\":\"2023-08-01T01:26:00Z\"}",
        "{\"product\":{\"productFamily\":\"Kinesis Streams\",\"attributes\":{\"regionCode\":\"us-east-1\",\"maximumExtendedStorage\":\"365 Days\",\"servic [...]

2023-10-25 23:55 UTC, Azanul approved these changes

2023-10-27 09:21 UTC, mlabouardy approved these changes

2023-10-27 09:33 UTC, merged