feat: fetch single resource by resource id
tailwarden/komiser pull request #1139
Opened 2023-10-26 16:12 UTC by shavidze

## Problem
There is no way atm to fetch a single resource via API. This would be useful for https://github.com/tailwarden/komiser/issues/1082 and https://github.com/tailwarden/komiser/issues/1072
## Solution

Fetch a single resource by ID

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-10-26 16:38 UTC, AvineshTripathi commented on handlers/resources_handler.go
> +	fmt.Println(resourceId)
```suggestion
```

2023-10-27 09:00 UTC, mlabouardy requested changes

2023-10-27 09:00 UTC, mlabouardy commented on internal/api/v1/endpoints.go
> +	router.GET("/resources", api.GetResourceByIdHandler)
why not pass the resource id as a path param?
`/resources/:id`

2023-10-27 09:05 UTC, shavidze commented on internal/api/v1/endpoints.go
> +	router.GET("/resources", api.GetResourceByIdHandler)
`id` is sometimes very complex and contains characters like / and other ones, that was a reason.

2023-10-30 14:19 UTC, mlabouardy approved these changes
All good!

2023-10-30 14:21 UTC, merged