#584 Added  Support for SSM based Instance
tailwarden/komiser pull request #1159
Opened 2023-11-03 08:10 UTC by Horiodino

## Problem

 #584

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-11-03 12:59 UTC, Azanul requested changes
Thanks for your contribution.
I've a few comments regarding the changes
- The changes belong to a new file in systemsmanager folder
- Take inspiration from how other`FetchDataFunction`s are written
- don't use "." imports

2023-11-16 05:39 UTC, Azanul requested changes
Drop the cost calculation as we'll be going with AWS cost explorer API integration for AWS provider

2023-11-17 14:54 UTC, Horiodino commented
> Drop the cost calculation as we'll be going with AWS cost explorer API integration for AWS provider

yep i removed the cost monitoring and will be doing test on it . any suggestion where i should i call the function from

2023-11-23 17:32 UTC, Horiodino commented
almost done with testing and going to do some changes :+1:

2023-11-24 04:22 UTC, Horiodino commented
@Azanul ```[
  {
    "id": ,
    "resourceId": "i-0b360c042863610a2",
    "provider": "AWS",
    "account": "mu-account",
    "accountId": "my-account-id",
    "service": "EC2",
    "region": "ap-south-1",
    "name": "t2.micro",
    "createdAt": "2023-11-24T02:22:33Z",
    "fetchedAt": "2023-11-24T09:45:21.242287061+05:30",
    "cost": 0,
    "metadata": null,
    "relations": null,
    "tags": [
      {
        "key": "Name",
        "value": "test"
      }
    ],
    "link": "https://ap-south-1.console.aws.amazon.com/ec2/home?region=ap-south-1#InstanceDetails:instanceId=i-0b360c042863610a2",
    "Value": ""
  }
]``` i tested the code but haven't committed the latest changes i , what is the id is here ?

2023-11-24 05:41 UTC, Azanul requested changes
failing CLI

2023-11-24 05:41 UTC, Azanul commented on providers/aws/systemsmanager/managedinstances.go
> +				Cost:       0.0, // No cost calculation in this version
```suggestion
```

2023-11-24 05:41 UTC, Azanul commented on providers/aws/systemsmanager/managedinstances.go
> +				Tags:       nil, // No tags in this version
```suggestion
```

2023-11-24 06:06 UTC, Horiodino commented
> failing CLI

its because i didn't committed latest changes , i am asking what should be in the 
```
"id": 
```
once the id is populated i will push the commits

2023-11-24 06:11 UTC, Azanul commented
> > failing CLI
> 
> its because i didn't committed latest changes , i am asking what should be in the
> 
> ```
> "id": 
> ```
> 
> once the id is populated i will push the commits

I think that's auto. It'll be filled by the respective DB.

2023-11-28 06:47 UTC, Azanul requested changes
- I see too many API requests being sent. Could you move client creation to the main function and create helper functions to fetch respective data for all instances at once instead of making an API call for each instance.
- refer to other implementations for error handling

2023-11-28 13:09 UTC, Horiodino commented
> * I see too many API requests being sent. Could you move client creation to the main function and create helper functions to fetch respective data for all instances at once instead of making an API call for each instance.
> * refer to other implementations for error handling

Ok

2023-12-26 09:09 UTC, Azanul approved these changes

2024-01-04 13:43 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +		MaxResults: aws.Int32(50),
Any reason we are keeping this parameter

2024-01-04 13:43 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +		log.Fatal(err)
```suggestion
		return resources, err
```

2024-01-04 13:43 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +		return nil, err
```suggestion
		return resources, err
```

some nits for readability

2024-01-04 13:43 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +		return nil, err
```suggestion
		return resources, err
```

2024-01-04 13:43 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +					Service:    "EC2",
should we call this `SSM Instance` ?

2024-01-04 16:48 UTC, Horiodino commented on providers/aws/systemsmanager/managedinstances.go
> +					Service:    "EC2",
yep, thanks for noticing it out 😃

2024-01-05 09:17 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +		MaxResults: aws.Int32(50),
In case of SSM managing more instances > 50 we would still need those too as we want users to know what resources in what quantity are active

2024-01-05 09:19 UTC, AvineshTripathi commented on providers/aws/systemsmanager/managedinstances.go
> +					Service:    "EC2",
Please donot add `-` and use space that is how we have done for other resources

2024-01-07 16:25 UTC, Horiodino commented on providers/aws/systemsmanager/managedinstances.go
> +		MaxResults: aws.Int32(50),
I didn't know that we have pagination token, let me add it so it will fetch all ssm intance evem its >50 👍

2024-01-07 16:26 UTC, Horiodino commented on providers/aws/systemsmanager/managedinstances.go
> +					Service:    "EC2",
ok

2024-01-07 17:42 UTC, Horiodino commented on providers/aws/systemsmanager/managedinstances.go
> +		MaxResults: aws.Int32(50),
@AvineshTripathi thanks for pointing it out ,  i removed the ```MaxResults``` because if the ssm-instance is less than 5 it will through error now just using ```pagination token``` 👍 .

2024-01-13 09:55 UTC, Azanul requested changes
Please fix the failing CI. You need to call getManagedEc2. Check out other implementations.

2024-01-24 07:56 UTC, Azanul commented
@Horiodino  Still failing

2024-01-24 08:30 UTC, Horiodino commented
> @Horiodino Still failing

in aws.go on line 103 i have added

2024-01-24 11:33 UTC, Azanul requested changes

2024-01-24 11:33 UTC, Azanul commented on providers/aws/systemsmanager/managedinstances.go
> +func getManagedEc2(ctx context.Context, client providers.ProviderClient) ([]models.Resource, error) {
```suggestion
func GetManagedEc2(ctx context.Context, client providers.ProviderClient) ([]models.Resource, error) {
```

2024-01-24 12:43 UTC, Horiodino commented
o i added it but i forgot to commit it , sorry

2024-01-24 13:26 UTC, Azanul approved these changes

2024-01-24 13:26 UTC, merged