fix(1255): Integrated the AWS costexplorer API
tailwarden/komiser pull request #1278
Opened 2023-12-12 08:11 UTC by tanbirali

## Problem
There are few AWS Services that are pending integration

## Solution

Filter out the correct resource and add to metdata field

## Changes Made

User the GetCostAndUsage to extract the cost and then added it to the metadata for the following services API for ec2, ecs, iam, s3, sqs, cloudfront, eks, elasticahce, redshift

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Reviewers

@Azanul

2023-12-12 10:53 UTC, Azanul approved these changes

2023-12-12 10:54 UTC, Azanul commented
Good work @tanbirali! It'd be great if you could implement the other ones also, if not then this PR looks GTG

2023-12-12 10:57 UTC, jakepage91 approved these changes

2023-12-12 14:38 UTC, tanbirali commented
I will be happy to contribute more

2023-12-12 17:29 UTC, jakepage91 commented
Thanks @tanbirali ! Much appreciated

2023-12-13 06:32 UTC, Azanul commented on providers/aws/sns/topics.go
>  	}
```suggestion
	stsOutput, err := stsClient.GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
	if err != nil {
		return resources, err
	}
	
	serviceCost, err := awsUtils.GetCostAndUsage(ctx, client.AWSClient.Region, "SNS")
	if err != nil {
		log.Warnln("Couldn't fetch SNS cost and usage:", err)
	}
```

2023-12-13 06:41 UTC, Azanul approved these changes
Although I haven't cross checked the service identifiers used (whether they're supported and whether they're supported under this name), I think we're GTG.

2023-12-13 10:41 UTC, jakepage91 requested changes
Thanks for the PR @tanbirali, have a few questions though.

2023-12-13 10:41 UTC, jakepage91 commented on providers/aws/dynamodb/tables.go
> +	serviceCost, err := awsUtils.GetCostAndUsage(ctx, client.AWSClient.Region, "DyanmoDB")
Looks like DynamoDB is misspelled here

2023-12-13 10:41 UTC, jakepage91 commented on providers/aws/systemsmanager/maintenance_window.go
> +	serviceCost, err := awsUtils.GetCostAndUsage(ctx, client.AWSClient.Region, "SystemManager")
Should it not be "SystemsManager" instead of "SystemManager"?

2023-12-13 10:41 UTC, jakepage91 commented on providers/aws/apigateway/apis.go
> +	serviceCost, err := awsUtils.GetCostAndUsage(ctx, client.AWSClient.Region, "ApiGateway")
When running `aws ce get-dimension-values` to retrieve the service value names, I see that the accepted service name value is the following: 

```
        {
            "Value": "Amazon API Gateway",
            "Attributes": {}
        },
```
Have you tested this out to make sure `ApiGateway` returns the expected value?

2023-12-13 10:41 UTC, jakepage91 commented on providers/aws/cloudfront/distributions.go
> +	serviceCost, err := awsUtils.GetCostAndUsage(ctx, client.AWSClient.Region, "CloudFront")
Same question here: 
```
"Value": "Amazon CloudFront"
```

2023-12-13 14:53 UTC, jakepage91 requested changes
Hey there @tanbirali , it looks like a lot of the service names do not follow the same naming returned by the costexplorer api, here is an snippet of the return 

```
{
    "DimensionValues": [
        {
            "Value": "AWS CloudTrail",
            "Attributes": {}
        },
        {
            "Value": "AWS Config",
            "Attributes": {}
        },
        {
            "Value": "AWS Cost Explorer",
            "Attributes": {}
        },
        {
            "Value": "AWS Data Transfer",
            "Attributes": {}
        },
        {
            "Value": "AWS Glue",
            "Attributes": {}
        },
        {
            "Value": "AWS Key Management Service",
            "Attributes": {}
        },
        {
            "Value": "AWS Lambda",
            "Attributes": {}
        },
        {
            "Value": "AWS Migration Hub Refactor Spaces",
            "Attributes": {}
        },
        {
            "Value": "AWS Secrets Manager",
            "Attributes": {}
        },
        {
            "Value": "AWS Service Catalog",
            "Attributes": {}
        },
        {
            "Value": "AWS Step Functions",
            "Attributes": {}
        },
```

Now, it might be the case that you have tested this already and the current service names work and actually return the service level cost metrics, could you confirm that to be the case? or else could you please change the names to the `aws ce get-dimension-values` call.

2023-12-15 11:37 UTC, tanbirali commented
I have made the changes of every aws services that I could find in that text file that contained the proper service name. But there are some services whose name were not present like for s3, codebuild, codedeploy etc. Let me if I need to make changes there.

2023-12-18 07:17 UTC, Azanul commented
> I have made the changes of every aws services that I could find in that text file that contained the proper service name. But there are some services whose name were not present like for s3, codebuild, codedeploy etc. Let me if I need to make changes there.

S3 = "Amazon Simple Storage Service"
codebuild = "AWS CodeBuild"
codedeploy = "AWS CodeCommit"

I think these will work and if not we can use `SERVICE_CODE`s instead of `SERVICE` dimension. I've listed all the service codesthat I could find [here](https://github.com/Azanul/til/blob/main/aws/service-codes.md)

2023-12-18 14:56 UTC, jakepage91 approved these changes
LGTM

2023-12-18 15:55 UTC, merged