Feature/1269 add shortcut to tailwarden in inventory table
tailwarden/komiser pull request #1306
Opened 2023-12-30 08:15 UTC by syedbarimanjan

## Problem

When a service is not supported, there is no interaction with the user, leading to confusion as the user may perceive the tool as broken.

## Solution

I created a `servicehelper` utility that stores all the providers and their services in an object. Two functions were implemented:

### 1. `checkIfServiceIsSupported(provider: string, service: string): boolean`
   - Takes a provider and service as parameters.
   - Returns a boolean indicating whether the service is supported for the given provider.

### 2. `checkIsSomeServiceUnavailable(receivedServices: string[]): boolean`
   - Takes an array of services as a parameter.
   - Returns a boolean indicating whether any service in the array is not supported.

In the `useInventory` hook, I added a new state to check if some service is unavailable. If there is something in the `searchedInventory` array, I loop over it and use the first function to check if even one element is not a supported service. If true, I set the state. If the `searchedInventory` is empty, I fetch all services from the API endpoint and use the second function to check if any service is not available. The result is set to the state.

Finally, the state is returned from the `useInventory` hook, and in the `InventoryPage`, it is destructured and passed to the `InventoryStatsCard`. If the state is true, an error icon is displayed, and clicking on it redirects to the Tailwarden page for more information.

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

I have updated the contributing guide to include a reminder for contributors to add any new provider or service to the list in the `serviceHelper` utility.

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@Azanul @jakepage91 @mlabouardy

2024-01-02 06:55 UTC, Azanul requested changes

2024-01-02 06:55 UTC, Azanul commented on dashboard/utils/serviceHelper.ts
> +  return services.includes(lowercaseService) ? true : false;
```suggestion
  return services.includes(lowercaseService);
```

2024-01-02 06:55 UTC, Azanul commented on dashboard/utils/serviceHelper.ts
> +export const allProvidersServices: { [key in Providers | string]: string[] } = {
```suggestion
export const allProvidersServices: { [key in Providers]: string[] } = {
```

`| string` part makes `key in Providers` redundant

2024-01-02 06:55 UTC, Azanul commented on CONTRIBUTING.md
> +
Close the code block

2024-01-02 07:29 UTC, syedbarimanjan commented on dashboard/utils/serviceHelper.ts
> +export const allProvidersServices: { [key in Providers | string]: string[] } = {
Oh forgot to change that

2024-01-02 07:42 UTC, syedbarimanjan commented
@Azanul did the changes.

2024-01-02 09:36 UTC, Azanul approved these changes

2024-01-02 09:41 UTC, Azanul commented
![Screenshot 2024-01-02 at 12 02 27 PM](https://github.com/tailwarden/komiser/assets/42029519/5fe6103a-0ab8-47d2-9a3f-1ffa5c2a93e7)

2024-01-02 12:08 UTC, AvineshTripathi commented
![image](https://github.com/tailwarden/komiser/assets/73980067/b17fc4d3-2b0c-45fd-9178-137d25d348e3)
I find the position to be odd can we move the icon inside the `discovered cost` part

2024-01-02 12:10 UTC, AvineshTripathi commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
Do you think having an api that returns the list of resources would be more better. I find this a bit redundant but open to discuss

2024-01-02 12:16 UTC, syedbarimanjan commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
there is an api which returns the services/resources which I am utilizing in the useInventory hook but the problem is how do we identify which one of those services which the user is using are not supported

2024-01-02 12:25 UTC, syedbarimanjan commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
one thing we could do is that change the /services api to return an object which has the name of the service and then another property which indicates if it is supported or not

2024-01-02 12:27 UTC, syedbarimanjan commented
> ![image](https://private-user-images.githubusercontent.com/73980067/293688549-b17fc4d3-2b0c-45fd-9178-137d25d348e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTc5MzYsIm5iZiI6MTcwNDE5NzYzNiwicGF0aCI6Ii83Mzk4MDA2Ny8yOTM2ODg1NDktYjE3ZmM0ZDMtMmIwYy00NWZkLTkxNzgtMTM3ZDI1ZDM0OGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGM0ZWM1OWVhNjdhZGFlZjUwYmE4MGI0NjE3OTI5NDU0OWI4M2Q4MzY5ZTg0YWM3NDZmOTc3ZWVjOTNjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fvF_jIWCnxGK2QYDygJSQYorBNnuoVrq1qM5DcwqgHw) I find the position to be odd can we move the icon inside the `discovered cost` part

It is what the designer designed

2024-01-02 13:19 UTC, AvineshTripathi commented
@AllieMendes whats your take on above

2024-01-03 16:59 UTC, AvineshTripathi commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
@Azanul do you think we can keep the cost field in db as null? if yes will it be a good choice(I feel that would be costly!) the main reason I want to do this is because there is manual work in adding the names in frontend too and I want to keep this as separate. Thoughts?

2024-01-03 18:04 UTC, syedbarimanjan commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
Indeed, that approach would work if the service/resource is not supported, the cost should be set to null or marked as unknown. This way, we can then handle errors accordingly. But it would be hard to check if the service is supported or not and then setting the cost to null, and that might even have some manual work init.

2024-01-04 13:00 UTC, AvineshTripathi commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
I think that should be a simple, we can convert the `cost` field of `Resource` schema to either be null or float value. This way we can have just call for resoources that have null value in it

2024-01-04 17:52 UTC, syedbarimanjan commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
> I think that should be a simple, we can convert the `cost` field of `Resource` schema to either be null or float value. This way we can have just call for resoources that have null value in it ref: https://bun.uptrace.dev/guide/models.html#nulls

Ok I havent used "go" but I will try and do this and can you confirm that are we using bun as an orm here.

2024-01-10 11:10 UTC, AvineshTripathi commented on dashboard/utils/serviceHelper.ts
> +export type Providers =
here https://github.com/tailwarden/komiser/blob/develop/models/resource.go and you can use above link

2024-01-16 09:59 UTC, mlabouardy commented
@Azanul could we merge this one?

2024-01-16 12:03 UTC, syedbarimanjan commented
> @Azanul could we merge this one?

I am working on implementing this the backend way as suggested by Avinesh but if this is all right then maybe I shouldn't?

2024-01-16 12:10 UTC, Azanul commented
> > @Azanul could we merge this one?
> 
> I am working on implementing this the backend way as suggested by Avinesh but if this is all right then maybe I shouldn't?

Although I agree with @AvineshTripathi, this PR looks good. We can work on the recommended changes on a different PR.
We can do the changes here as well, depending completely on your availability.

2024-01-16 13:38 UTC, syedbarimanjan commented
> > > @Azanul could we merge this one?
> > 
> > 
> > I am working on implementing this the backend way as suggested by Avinesh but if this is all right then maybe I shouldn't?
> 
> Although I agree with @AvineshTripathi, this PR looks good. We can work on the recommended changes on a different PR. We can do the changes here as well, depending completely on your availability.

I will INSHAALLAH commit the changes in some days.

2024-01-25 02:18 UTC, syedbarimanjan commented
> > > @Azanul could we merge this one?
> > 
> > 
> > I am working on implementing this the backend way as suggested by Avinesh but if this is all right then maybe I shouldn't?
> 
> Although I agree with @AvineshTripathi, this PR looks good. We can work on the recommended changes on a different PR. We can do the changes here as well, depending completely on your availability.

Can you just merge this one when I get time I will raise a new pr for implementing this the backend way.

2024-01-25 06:56 UTC, Azanul approved these changes

2024-01-27 17:11 UTC, syedbarimanjan commented
> > @Azanul could we merge this one?
> 
> Yes, another approval is needed

@mlabouardy

2024-01-27 18:08 UTC, AvineshTripathi approved these changes

2024-01-28 05:39 UTC, merged