Aws services
tailwarden/komiser pull request #1353
Opened 2024-02-23 05:51 UTC by Azanul

## Problem

Missing AWS services Cloudtrail, SecretsManger and DataSync

## Solution

Added respective services

## Notes

I couldn't create a DataSync agent so I've left it to point to the list page

2024-02-23 12:32 UTC, mlabouardy requested changes
could you include those functions [here](https://github.com/tailwarden/komiser/blob/develop/providers/aws/aws.go)
also include the new permissions to the IAM policy [here](https://github.com/tailwarden/komiser/blob/develop/policy.json)

2024-02-23 12:45 UTC, Azanul commented
> here

Thanks a lot for pointing it out

2024-02-26 13:25 UTC, mlabouardy approved these changes

2024-02-26 16:18 UTC, AvineshTripathi reviewed
rest LGTM

2024-02-26 16:18 UTC, AvineshTripathi commented on providers/aws/cloudtrail/trail.go
> +	output, err := neptuneClient.ListTrails(ctx, &config)
```suggestion
	output, err := neptuneClient.ListTrails(ctx, &params)
```

2024-02-26 16:18 UTC, AvineshTripathi commented on providers/aws/cloudtrail/trail.go
> +			Name:       trailName,
as per code in case `trail.Name` is nil Name field would be "" and so the frontend will show empy name

2024-02-26 16:18 UTC, AvineshTripathi commented on providers/aws/datasync/agents.go
> +	var config datasync.ListAgentsInput
same as above

2024-02-26 16:21 UTC, Azanul commented on providers/aws/cloudtrail/trail.go
> +	output, err := neptuneClient.ListTrails(ctx, &config)
I don't get it

2024-02-26 18:13 UTC, AvineshTripathi commented on providers/aws/cloudtrail/trail.go
> +	output, err := neptuneClient.ListTrails(ctx, &config)
the name should be params or input and not config

2024-02-26 18:15 UTC, AvineshTripathi commented on providers/aws/cloudtrail/trail.go
> +			Name:       trailName,
it would seem like a bug on frontend side but I am okay if you want to keep it empty

2024-02-27 03:42 UTC, Azanul commented on providers/aws/cloudtrail/trail.go
> +	output, err := neptuneClient.ListTrails(ctx, &config)
we've used config everywhere else, so just maintaining the consistency

2024-02-27 03:43 UTC, Azanul commented on providers/aws/cloudtrail/trail.go
> +			Name:       trailName,
I think empty is fine

2024-02-27 04:57 UTC, Azanul commented
> apologies for delay

No worries, happens to the best of us

2024-02-27 10:17 UTC, merged