create local network gateway resource
tailwarden/komiser pull request #1457
Opened 2024-07-07 00:02 UTC by azgcloudev

## Problem

Solving Issue #396 

## Solution
Adding resource

## Changes Made
added local network gateway
also created a function to get the resource groups in the subscription to be able to call all the local network gateways, as function do not call under a subscription level

## How to Test

Added a new local network gateway in the Azure subscription, test if it shows successfully in Komiser. Cost is not showing, as LNGs do not generate cost.

## Screenshots
<img width="1301" alt="image" src="https://github.com/tailwarden/komiser/assets/72358828/4513bcd7-82e6-4ba5-bdd0-a70f1792a8cb">

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@jakepage91

2024-07-07 06:53 UTC, AvineshTripathi commented on providers/azure/resourcegroup/resource_groups.go
> +			resourceGroupNames = append(resourceGroupNames, *resourceGroup.Name)
can you also add other details like https://github.com/tailwarden/komiser/pull/1457/files#diff-e34e11157def2d0cf86866b6de46e377bda2def7d4aa338041dac225c5a1e7cfR56

2024-07-07 06:55 UTC, AvineshTripathi commented on providers/azure/networking/local_network_gateways.go
> +					Link:       fmt.Sprint("https://portal.azure.com/#resource%s", *lng.ID),
can we fix the failure?

2024-07-07 17:18 UTC, azgcloudev commented on providers/azure/networking/local_network_gateways.go
> +					Link:       fmt.Sprint("https://portal.azure.com/#resource%s", *lng.ID),
fixed

2024-07-07 17:19 UTC, azgcloudev commented on providers/azure/resourcegroup/resource_groups.go
> +			resourceGroupNames = append(resourceGroupNames, *resourceGroup.Name)
I made the change to add the resource as a model and not the string and fill the details.

However I do not added to to listOfSupportedServices as a resource group is not a provider.

2024-07-08 16:35 UTC, AvineshTripathi approved these changes

2024-07-08 22:40 UTC, Azanul requested changes
other than this nit, LGTM

2024-07-08 22:40 UTC, Azanul commented on dashboard/utils/serviceHelper.ts
> +    'Local Network Gateway'
small case

2024-07-08 23:07 UTC, azgcloudev commented on dashboard/utils/serviceHelper.ts
> +    'Local Network Gateway'
fixed

2024-07-08 23:19 UTC, Azanul approved these changes

2024-07-08 23:40 UTC, merged