feat: added dependency support to k8s
tailwarden/komiser pull request #1487
Opened 2024-08-07 19:15 UTC by AvineshTripathi

Some relationships are complex to generate and would create redundancy because, in the current arch, we fetch all the objects separately and without any connection, and in some cases, we need both resources to be present in order to validate the relations. 

To avoid this, we should have something like a stitching module that would asynchronously join the node based on a predefined condition. Open to discussion

2024-08-08 04:50 UTC, Azanul commented
We can create a routine which will start when all the resources(k8s) from the wait group are completed

2024-08-16 00:35 UTC, Azanul requested changes
1. Why are we only using cache for services?
2. address lint issue
3. Let's maintain a clear document to keep track of what changes we're making and how it'll reflect on the dependency graph

2024-08-16 00:35 UTC, Azanul commented on internal/config/load.go
> +)
constants declared twice

2024-08-16 00:35 UTC, Azanul commented on internal/config/load.go
> +				Cache:     cache.New(CACHE_DURATION, CLEANUP_DURATION),
nit: keep consistent code style

2024-08-16 00:35 UTC, Azanul commented on providers/k8s/k8s.go
> +					_, err = db.NewInsert().Model(&resource).On("CONFLICT (resource_id) DO UPDATE").Set("cost = EXCLUDED.cost, relations=EXCLUDED.relations").Exec(context.Background())
explain

2024-08-16 05:56 UTC, AvineshTripathi commented on providers/k8s/k8s.go
> +					_, err = db.NewInsert().Model(&resource).On("CONFLICT (resource_id) DO UPDATE").Set("cost = EXCLUDED.cost, relations=EXCLUDED.relations").Exec(context.Background())
if the resource or the relation was deleted, in the next cycle it will not be included if this is not added

2024-08-16 05:59 UTC, AvineshTripathi commented
> 1. Why are we only using cache for services?
Since we have to get list of all the services to find the relation between pod and services, a new call to the service list has to be done. However we already have a service fetcher and since services might be used for other relations, i felt it would be better if we cache it for some time to avoid multiple calls.

This I feel can be used across the project  to find relations where presence of other resource is mandatory.
> 2. address lint issue
Will do 
> 3. Let's maintain a clear document to keep track of what changes we're making and how it'll reflect on the dependency graph
where should we document

2024-08-16 06:05 UTC, Azanul commented on providers/k8s/k8s.go
> +					_, err = db.NewInsert().Model(&resource).On("CONFLICT (resource_id) DO UPDATE").Set("cost = EXCLUDED.cost, relations=EXCLUDED.relations").Exec(context.Background())
`cost = EXCLUDED.cost` means that if a conflict occurs, the cost column of the existing row will be updated with the value from the new row being inserted. Same goes for relations

2024-08-16 06:10 UTC, Azanul commented
> Since we have to get list of all the services to find the relation between pod and services, a new call to the service list has to be done. However we already have a service fetcher and since services might be used for other relations, i felt it would be better if we cache it for some time to avoid multiple calls.

Is the case different for nodes, pods, etc.?

> where should we document

Let's create a documentation page for dependency graph that'll help users to navigate the graph easily. Like a user guide

2024-08-16 06:12 UTC, AvineshTripathi commented on providers/k8s/k8s.go
> +					_, err = db.NewInsert().Model(&resource).On("CONFLICT (resource_id) DO UPDATE").Set("cost = EXCLUDED.cost, relations=EXCLUDED.relations").Exec(context.Background())
thats correct and we want to ensure this field gets updated

2024-08-16 06:13 UTC, AvineshTripathi commented
> > Since we have to get list of all the services to find the relation between pod and services, a new call to the service list has to be done. However we already have a service fetcher and since services might be used for other relations, i felt it would be better if we cache it for some time to avoid multiple calls.
> 
> Is the case different for nodes, pods, etc.?
> 


Didnt get you here

2024-08-16 14:02 UTC, Azanul commented
> > > Since we have to get list of all the services to find the relation between pod and services, a new call to the service list has to be done. However we already have a service fetcher and since services might be used for other relations, i felt it would be better if we cache it for some time to avoid multiple calls.
> > 
> > 
> > Is the case different for nodes, pods, etc.?
> 
> Didnt get you here

What's stopping us from caching nodes and pods too?

2024-08-16 14:05 UTC, AvineshTripathi commented
In case of nodes and pod we do get fields to get the relation in there as comparison is not required while in case of service its not the case. Let me know if that answers your question

2024-08-16 14:09 UTC, Azanul commented
> In case of nodes and pod we do get fields to get the relation in there as comparison is not required while in case of service its not the case. Let me know if that answers your question

It does, thanks

2024-08-17 08:10 UTC, Azanul approved these changes

2024-08-19 15:36 UTC, merged