Add DigitalOcean VPC resource
tailwarden/komiser pull request #293
Opened 2023-01-21 20:19 UTC by nemca

### Description
Add DigitalOcean VPC resource.

2023-01-21 20:49 UTC, nemca commented
I found [issue](https://github.com/tailwarden/komiser/issues/253) for this changes.

2023-01-23 11:18 UTC, mlabouardy requested changes

2023-01-23 11:18 UTC, mlabouardy commented on providers/digitalocean/digitalocean.go
> +		network.Vpcs,
related to https://github.com/tailwarden/komiser/pull/291#discussion_r1083928847

2023-01-23 11:18 UTC, mlabouardy commented on providers/digitalocean/network/vpcs.go
> +		log.Printf("[%s][DigitalOcean] %s", client.Name, err)
why not return the `err`?

2023-01-23 11:57 UTC, nemca commented on providers/digitalocean/network/vpcs.go
> +		log.Printf("[%s][DigitalOcean] %s", client.Name, err)
I think this is not a critical error and you should not interrupt the function if it was not possible to get the list of regions.
The code below will use the slug name if the fully qualified region name is not found.

2023-01-23 12:01 UTC, mlabouardy commented on providers/digitalocean/network/vpcs.go
> +		log.Printf("[%s][DigitalOcean] %s", client.Name, err)
In this case, can you change the log type, maybe with log.Warn("")

2023-01-23 12:14 UTC, nemca commented on providers/digitalocean/network/vpcs.go
> +		log.Printf("[%s][DigitalOcean] %s", client.Name, err)
Fixed.

2023-01-23 16:48 UTC, mlabouardy approved these changes
LGTM

2023-01-23 16:48 UTC, merged