Add Tencent provider
tailwarden/komiser pull request #308
Opened 2023-01-28 23:20 UTC by nemca

### Description
Added initial version of Tencent provider with Instance resources.

2023-01-29 18:55 UTC, mlabouardy requested changes
Thanks a million for the contributions, could you please address my comment :)

2023-01-30 12:27 UTC, nemca commented
> Thanks a million for the contributions, could you please address my comment :)

Which one comment?

2023-01-30 12:29 UTC, mlabouardy commented on providers/tencent/tencent.go
> +	for _, fetchResources := range listOfSupportedServices() {
can you fetch the resources from other regions, see CIVO integration as an example: https://github.com/tailwarden/komiser/blob/master/providers/civo/civo.go#L33

2023-01-30 12:29 UTC, mlabouardy commented on providers/tencent/tencent.go
> +	for _, fetchResources := range listOfSupportedServices() {
@nemca this one :)

2023-01-30 12:57 UTC, nemca commented on providers/tencent/tencent.go
> +	for _, fetchResources := range listOfSupportedServices() {
Done.

2023-01-30 14:40 UTC, mlabouardy approved these changes

2023-01-30 14:41 UTC, merged