New PR Template
tailwarden/komiser pull request #354
Opened 2023-02-11 11:14 UTC by ShivamTyagi12345

This pull request proposes to add a new template for pull requests to the repository. The new template provides a clear and concise format for contributors to follow when submitting changes to the codebase. The template includes sections for describing the problem, solution, changes made, instructions for testing, relevant screenshots, notes, and a checklist.

The goal of this pull request is to ensure that all pull requests have a consistent format and provide enough information for reviewers to easily understand the changes and assess their impact on the codebase. This will help streamline the review process, reduce the time spent on reviewing, and increase the overall efficiency of the development workflow.

The new template has been designed to be flexible and can be customized to suit the specific needs of the repository. The proposed template is well-documented and provides a clear structure for contributors to follow, helping them to present their changes in a professional and organized manner.

2023-02-12 19:39 UTC, mlabouardy requested changes
Thanks @ShivamTyagi12345, request small changes to improve the template

2023-02-12 19:39 UTC, mlabouardy commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Documentation has been updated, if necessary
can you link it to https://github.com/tailwarden/docs.komiser.io repo

2023-02-12 19:39 UTC, mlabouardy commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Code follows the code style and formatting guidelines
can you link it to https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md

2023-02-13 03:44 UTC, ShivamTyagi12345 commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Documentation has been updated, if necessary
done

2023-02-13 13:55 UTC, mlabouardy approved these changes
Thanks for the changes!

2023-02-13 13:55 UTC, merged