Add component tests to Card
tailwarden/komiser pull request #591
Opened 2023-03-07 17:39 UTC by victorgaard

## Changes Made
- Added tests for our Card component
- Test covers:
  - If card is rendered without crashing
  - If card renders the icon
  - If card renders the value in the correct format
  - If card renders the value in the correct format (currency)
  - If card display the tooltip if tooltip is passed as props

## How to Test
- `npm run test:watch` from `dashboard` folder
- press `p`
- enter `card` as pattern

## Screenshots
- `Card test`
<img width="462" alt="image" src="https://user-images.githubusercontent.com/13384559/223503253-8cb31e43-b9d5-4420-bbaf-45185902df86.png">

2023-03-08 09:09 UTC, eneskaya commented
@victorgaard Just to be clear, *component testing* usually refers to testing with [Cypress](https://docs.cypress.io/guides/component-testing/overview). The tests that we can write with Jest/testing-library are still unit tests, testing components. Just so we don't get mixed up in the wording 😅 👍

2023-03-08 09:37 UTC, eneskaya requested changes

2023-03-08 09:37 UTC, eneskaya commented on dashboard/components/card/Card.test.tsx
> +  test('should render card component', () => {
[optional] 
suggestion for test naming: `should render card component without crashing`

2023-03-08 09:37 UTC, eneskaya commented on dashboard/components/card/Card.test.tsx
> +    const formattedNumber = screen.getByRole('formattedNumber');
The html `role` attribute is actually meant to be used for accessibility reasons (I'm no expert on that tbh) and there is a set of values that should be used for that, see the [MDN docs on that](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles). Also note what the documentation of `testing-library` has to say about that:

> Please note that setting a role and/or aria-* attribute that matches the implicit ARIA semantics is unnecessary and is not recommended as these properties are already set by the browser, and we must not use the role and aria-* attributes in a manner that conflicts with the semantics described. For example, a button element can't have the role attribute of heading, because the button element has default characteristics that conflict with the heading role.

I would suggest to either

1. just assert that the text is showing *somewhere* by using [`getByText`](https://testing-library.com/docs/queries/bytext)
2. assigning a `data-testid` if you can't find the element any other way

I think in this case we could just go with the first approach, I would suggest only the second option if there is no other way of finding elements.

2023-03-08 12:08 UTC, mlabouardy requested changes

2023-03-08 12:08 UTC, mlabouardy commented on dashboard/package.json
> +    "@testing-library/react": "^14.0.0"
shouldn't this one be in dev dependencies?

2023-03-09 09:32 UTC, victorgaard commented on dashboard/components/card/Card.test.tsx
> +    const formattedNumber = screen.getByRole('formattedNumber');
Thanks for sharing! Just changed them from `role` to `data-testid`, except for tooltip which I think it's still relevant for accessibility as its role is not set by the browser. Wdyt?

2023-03-09 09:37 UTC, victorgaard commented on dashboard/components/card/Card.test.tsx
> +  test('should render card component', () => {
Done

2023-03-09 09:42 UTC, victorgaard commented on dashboard/package.json
> +    "@testing-library/react": "^14.0.0"
The build fails if it's not in the dependencies. Lemme dig into it

```
./components/card/Card.test.tsx
1:1  Error: '@testing-library/react' should be listed in the project's dependencies, not devDependencies.
```

2023-03-09 09:52 UTC, eneskaya commented on dashboard/package.json
> +    "@testing-library/react": "^14.0.0"
This issue could help https://github.com/airbnb/javascript/issues/2376

2023-03-09 10:00 UTC, victorgaard commented on dashboard/package.json
> +    "@testing-library/react": "^14.0.0"
Just the airbnb base config doesn't work, but I added this extra rule in the array and it seems to work:
`"**/*test.{ts,tsx}", // komiser tests`

Lemme push to see if it passes

2023-03-09 10:02 UTC, victorgaard commented on dashboard/package.json
> +    "@testing-library/react": "^14.0.0"
Seems to be working! :)

2023-03-09 10:07 UTC, eneskaya commented on dashboard/.eslintrc.json
> +          "**/karma.conf.js", // karma config
you can safely remove these

2023-03-09 10:11 UTC, victorgaard commented on dashboard/.eslintrc.json
> +          "**/karma.conf.js", // karma config
Done

2023-03-09 10:22 UTC, mlabouardy approved these changes

2023-03-09 10:23 UTC, merged