feat: add csv export endpoint for resources
tailwarden/komiser pull request #619
Opened 2023-03-14 11:28 UTC by eneskaya

## Problem

[Provide a brief description of the problem that you are trying to solve with this pull request.]

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-03-15 11:10 UTC, eneskaya commented
@victorgaard The route to download the csv for a given view has slightly changed to `GET /resources/export-csv/{viewId}` now

2023-03-15 15:36 UTC, mlabouardy requested changes

2023-03-15 15:36 UTC, mlabouardy commented on models/resource.go
> +	ResourceId string            `json:"resourceId" bun:"resource_id,unique" csv:"provider"`
why `csv:provider`? same for `id` why its needed?

2023-03-15 15:38 UTC, eneskaya commented on models/resource.go
> +	ResourceId string            `json:"resourceId" bun:"resource_id,unique" csv:"provider"`
good catch, it's not needed :D

2023-03-16 08:35 UTC, mlabouardy approved these changes

2023-03-16 08:35 UTC, merged