added dashboard contributor video to dashboard readme
tailwarden/komiser pull request #629
Opened 2023-03-15 19:20 UTC by jakepage91

Hey there @victorgaard 

Added the walkthrough video to the readme if that is cool with you.

2023-03-16 10:47 UTC, victorgaard requested changes

2023-03-16 10:47 UTC, victorgaard commented on dashboard/README.md
> +<div style={{
Hey @jakepage91 I'm seeing this when viewing the README file:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/13384559/225593083-983c7fc1-86fe-432f-8b77-ec06bcba3380.png">

I believe GitHub doesn't accept iframes in its markdown. Maybe we could leverage something like adding the thumbnail as image and a link to the youtube video?

An example: https://gist.github.com/bitsurgeon/acd769ae3236c48a433e0acb11784c2e

2023-03-16 12:07 UTC, jakepage91 commented on dashboard/README.md
> +<div style={{
Thanks! you might be right. I thought it might work since in the documentation this notation is the one used in the markdown files for the documentation. Let me try out your proposal. Obrigado!

2023-03-17 11:36 UTC, mlabouardy approved these changes

2023-03-17 11:40 UTC, merged