Collecting MongoDB Serverless clusters
tailwarden/komiser pull request #634
Opened 2023-03-16 14:27 UTC by AnnuCode

## Problem

Missing collection of MongoDB Atlas Serverless clusters. 

## Solution

Created a new `serverlessInstances` package to collect all the MongoDB Atlas Serverless clusters.

## Changes Made

`serverlessInstances` package added in the mongdbatlas `providers` along with its test file (`serverlessinstances_test.go`) which at present checks `NormalizeRegionNames` function only. 

## How to Test

The new `serverlessInstances` package can be tested by running `go test` in the `serverlessinstances` directory.

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [x] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@eneskaya

2023-03-17 07:15 UTC, eneskaya requested changes

2023-03-17 07:15 UTC, eneskaya commented on providers/mongodbatlas/serverlessinstances/serverlessinstances.go
> +}
This function already exists in the `clusters` package, and should not be duplicated (esp. with the tests). You can pull the function up into `mongodbatlas` package, export it from there and use it in both `clusters` and `serverlessInstances` package

2023-03-17 07:15 UTC, eneskaya commented on providers/mongodbatlas/serverlessinstances/serverlessinstances.go
> +package serverlessInstances
The package name should not be camelCased, you could just use `serverless`. Please see also the Go documentation regarding package names: https://go.dev/blog/package-names

2023-03-17 07:15 UTC, eneskaya commented on providers/mongodbatlas/serverlessinstances/serverlessinstances_test.go
> +func TestNormalizeRegionNames(t *testing.T) {
This test would move together with the `normalizeRegionNames` to the parent package. You can then remove the duplication

2023-03-17 11:23 UTC, mlabouardy commented
@AnnuCode let me know if you need a hand to make those changes so I can include your PR in this week release :)

2023-03-17 11:46 UTC, AnnuCode commented
> @AnnuCode let me know if you need a hand to make those changes so I can include your PR in this week release :)
 Thanks @mlabouardy, I think I will be able to do it and trying to get it done by today itself. I will surely let you know if I get stuck :)

2023-03-17 14:19 UTC, AnnuCode commented on providers/mongodbatlas/serverlessinstances/serverlessinstances.go
> +}
@eneskaya I have transferred the duplicated function(`normalizeRegionName`) in `mongodbatlas` package and then imported to use it in `serverless` (changed the name from `serverlessInstances` to `serverless`) package. However, I couldn't import and use the function `NormalizeRegionName` in `clusters` package because of Import Cycles as `clusters` package is already imported in `mongodbatlas` package. Hence, I repeated the function code and couldn't refactor the `clusters` package for now. Maybe the Import Cycles can be [dealt](https://jogendra.dev/import-cycles-in-golang-and-how-to-deal-with-them) with Interfaces?

2023-03-21 10:04 UTC, eneskaya commented on providers/mongodbatlas/serverlessinstances/serverlessinstances.go
> +package serverless
The file name should be the same as the pkg name, please rename to `.../serverless.go`

2023-03-21 10:04 UTC, eneskaya commented on providers/mongodbatlas/serverlessinstances/serverlessinstances.go
> +}
@AnnuCode Sorry for coming back to this so late. You're absolutely right, importing the `mongodbatlas` pkg creates a cycle here, which we don't want. This function would be a good candidate then to live in the `utils` package, IMHO. What do you think?

2023-03-21 14:32 UTC, eneskaya commented
> @eneskaya Hi, I made the changes as suggested and lost all my commits after doing `git reset --hard master@{"10 minutes ago"}`. Not the best start of the evening for me. Trying to get back ...

Oh man, sorry to hear! Should I close the PR then for now? You can open another one as soon as you're ready.

2023-03-21 14:44 UTC, mlabouardy commented
> @eneskaya Hi, I made the changes as suggested and lost all my commits after doing `git reset --hard master@{"10 minutes ago"}`. Not the best start of the evening for me. Trying to get back ...

have you tried reverting the reset, you can still get back your changes if git hasn't garbage collected yet. Have you tried `git reflog`, do you see your commits there? if yes you can then `git reset --hard COMMIT_ID`

2023-03-21 14:50 UTC, AnnuCode commented
@mlabouardy Hi, yes just did this and got my commits back. Thanks. Now I'm back to my original issue (because of which I used the `hard reset` command in the first place: I am getting an error saying, can't push because tip of my branch is behind its remote counterpart. I tried to do git pull but it says there is no tracking info for this branch. I guess I should do this: `git branch --set-upstream-to=origin/<branch> feature/618` ?

2023-03-21 15:34 UTC, AnnuCode commented
@eneskaya Yes I think it's a good idea to close this PR. I'll try to commit again correctly. Thanks for all the support.

2023-03-21 15:34 UTC, closed without merging