Fix release workflow
tailwarden/komiser pull request #643
Opened 2023-03-20 14:28 UTC by eneskaya

This PR finalizes the automation of our release process, with `goreleaser` it now generates

- a release draft, including all the build archives
- a push to `homebrew-komiser` to update the Formula version
- a push to docker hub including the latest, version and gitcommit tag
- a push to our `helm` repository, bumping the version

2023-03-20 21:59 UTC, mlabouardy commented on .github/workflows/release.yml
> +          git commit -m "Bump version to 3.0.7"
the version should be dynamic not hardcoded
also, could we follow the git commit format `chore: bump version v3.0.7`

2023-03-20 21:59 UTC, mlabouardy commented on .goreleaser.yaml
> +      - goos: linux
why arm64 for linux is skipped?

2023-03-21 07:58 UTC, eneskaya commented on .goreleaser.yaml
> +      - goos: linux
I oriented myself on the circleci build steps, where this os/arch wasn't build as far as I could see. Should I enable?

2023-03-21 08:10 UTC, mlabouardy commented on .goreleaser.yaml
> +      - goos: linux
make sense, no all good then

2023-03-21 08:11 UTC, mlabouardy commented on Dockerfile
> +ENV VERSION $VERSION
btw, you'll need to declare the VERSION as an ARG (see line 4 for reference)

2023-03-21 08:27 UTC, eneskaya commented on Dockerfile
> +ENV VERSION $VERSION
Thanks for the hint!

2023-03-21 10:16 UTC, mlabouardy requested changes

2023-03-21 10:16 UTC, mlabouardy commented on .goreleaser.yaml
> +      - --build-arg=SEGMENT_WRITE_KEY=$SEGMENT_WRITE_KEY
you need to pass the VERSION here as well: `- --build-arg=VERSION={{ .Version }}`

2023-03-21 10:31 UTC, mlabouardy approved these changes

2023-03-21 10:33 UTC, merged