Tech 1048/cacluate cost elastic ip
tailwarden/komiser pull request #703
Opened 2023-04-04 18:57 UTC by jakepage91

Hey there! 

I've added a cost calculation part for Elastic IPs here. But, the AWS Go SDK doesn't let me find the exact creation time of the Elastic IP. So, I've come up with a workaround that calculates the cost of unassociated Elastic IPs from the moment they're first fetched. This isn't perfect, though, as it may give inaccurate cost calculations. Unassociated IP addresses will only start counting towards the cost after Komiser fetches them, which could lead to underestimating the actual costs.

Can you think of any better way? 
Cheers

2023-04-05 07:44 UTC, eneskaya approved these changes

2023-04-05 07:47 UTC, eneskaya commented on providers/aws/ec2/elastic-ips.go
> +			hoursSinceFetched := hoursSince(fetchedAt)
Wait, I approved but now I just saw, that this will be always `0` hours, hence 0$ monthly cost

2023-04-05 08:30 UTC, mlabouardy requested changes
You can get the creation date of the IP by leveraging AWS Config. 
This command should return the creation date (under `configurationItemCaptureTime` attribute):
` aws configservice batch-get-resource-config --resource-keys resourceType=AWS::EC2::EIP,resourceId=eipalloc-ID_HERE`

![Screenshot 2023-04-05 at 10 29 48](https://user-images.githubusercontent.com/10320205/230025988-f1ea8b39-84f1-4fa2-a749-a53562f2b5ea.png)

2023-04-06 13:37 UTC, jakepage91 commented
Hey there @eneskaya and @mlabouardy just to let you know that I made some updates (thanks for the help Moh!)

2023-04-07 08:13 UTC, mlabouardy approved these changes
@jakepage91 I've added missing AWS permission to IAM policy file as well handled when the permission is missing otherwise the resource won't be collected

2023-04-07 08:13 UTC, merged