patched elastic ip ResourceCreation nil pointer
tailwarden/komiser pull request #716
Opened 2023-04-10 15:44 UTC by jakepage91

## Problem

```
komiser-komiser-1  | panic: runtime error: index out of range [0] with length 0
komiser-komiser-1  | 
komiser-komiser-1  | goroutine 23 [running]:
komiser-komiser-1  | github.com/tailwarden/komiser/providers/aws/ec2.ElasticIps({0x339e8e0, 0xc0001b0070}, {0xc0006c90e0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
komiser-komiser-1  |     /home/runner/work/komiser/komiser/providers/aws/ec2/elastic-ips.go:65 +0xe4f
komiser-komiser-1  | github.com/tailwarden/komiser/providers/aws.FetchResources({_, _}, {0xc0006c90e0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}, ...)
komiser-komiser-1  |     /home/runner/work/komiser/komiser/providers/aws/aws.go:84 +0x4d5
komiser-komiser-1  | github.com/tailwarden/komiser/internal.fetchResources.func1({0x339e8e0?, 0xc0001b0070?}, {0xc0006c90e0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}, ...)
komiser-komiser-1  |     /home/runner/work/komiser/komiser/internal/internal.go:246 +0x1e9
komiser-komiser-1  | created by github.com/tailwarden/komiser/internal.fetchResources
komiser-komiser-1  |     /home/runner/work/komiser/komiser/internal/internal.go:240 +0x109e
```
go runtime panic caused by ReasourceCreationTime nil pointer
## Solution

- Added additional check for `elasticIps.AllocationId` being nil.
- Added extra error checking `resourceConfig.BaseConfigurationItems` if a nil is detected a warning is logged and cost is set to 0.
- Also if `resourceConfig.BaseConfigurationItems[0].ResourceCreationTime` is nil, a warning is logged and cost is set to 0.
- tags nil pointer check

2023-04-11 09:16 UTC, eneskaya commented on providers/aws/ec2/elastic-ips.go
> +				if tag.Key != nil && tag.Value != nil {
Just curious, was this making any problems? Because we do this everywhere

2023-04-11 10:22 UTC, mlabouardy requested changes

2023-04-11 10:22 UTC, mlabouardy commented on providers/aws/ec2/elastic-ips.go
> +				if len(resourceConfig.BaseConfigurationItems) > 0 {
for me only this check is needed, the previous ones could be removed :)

2023-04-12 04:53 UTC, AvineshTripathi commented on providers/aws/ec2/elastic-ips.go
> +				if tag.Key != nil && tag.Value != nil {
if there is a tag existing in the resource why would its key or value or maybe both be a nil value?

2023-04-12 04:57 UTC, AvineshTripathi commented on providers/aws/ec2/elastic-ips.go
> +				if len(resourceConfig.BaseConfigurationItems) > 0 {
I am curious to know when can len of `BaseConfigurationItems` arr be 0, is it when there is no resource present in the account? for me confusion here is if there is no resource then we should not reach to the line as the line 41 is an iteration of address and as there is no resource there should not be any addressess

p.s. I haven't tried this locally and so may be thinking wrong, please correct me

2023-04-14 13:54 UTC, mlabouardy commented on providers/aws/ec2/elastic-ips.go
> +				if len(resourceConfig.BaseConfigurationItems) > 0 {
@AvineshTripathi the issue is related to AWS Config since we use it to fetch the creation date of the IP resource. For some cases, the `BaseConfigurationItems` array can be empty for some IPs (couldn't produce it yet though)

2023-04-14 13:54 UTC, mlabouardy commented
I'll close this PR since its too verbose with checks 😆 I've opened a PR to check only `BaseConfigurationItems` array size

2023-04-14 13:54 UTC, closed without merging