RDS Proxies
tailwarden/komiser pull request #808
Opened 2023-05-23 13:18 UTC by AnnuCode

## Problem

fixes #564 

## Solution

Adding support to collect Amazon RDS db-proxy.

## Changes Made

- added `proxies.go` file in the `rds` folder.

## Notes

- want to confirm if we can `tag` the RDS Proxy, this [link](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Tagging.html) provides more info.
- want to find the correct format for `Link` in the `Resources` slice.

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-05-30 08:07 UTC, mlabouardy commented
@AnnuCode do you need some help for this one? :)

2023-05-30 08:19 UTC, AnnuCode commented
@mlabouardy Hi, can you please share the correct format of  RDS Proxy url to be used as `LINK` in the `resources` slice?

2023-06-06 10:27 UTC, mlabouardy commented
> @mlabouardy Hi, can you please share the correct format of RDS Proxy url to be used as `LINK` in the `resources` slice?

Hey @AnnuCode, the format is the following:
`https:/REGION.console.aws.amazon.com/rds/home?region=REGION#proxies:PROXY_NAME`

2023-06-07 09:05 UTC, mlabouardy requested changes
Minor change on copy :)

2023-06-07 09:05 UTC, mlabouardy commented on providers/aws/rds/proxies.go
> +				Service:    "RDS Instance",
should be a "RDS Proxy"

2023-06-07 09:05 UTC, mlabouardy commented on providers/aws/rds/proxies.go
> +		"service":   "RDS Instance",
"RDS Proxy"

2023-06-07 19:26 UTC, mlabouardy approved these changes
LGTM!

2023-06-07 19:26 UTC, merged