Custom Webhook Integration
tailwarden/komiser pull request #826
Opened 2023-05-28 18:21 UTC by ShubhamPalriwala

## Problem
Till now, users could only add Slack Alerts, this PR introduces the ability to add custom webhooks extensively.

## Solution
- Add Custom Webhooks
- Ability to test the webhook endpoint before adding it and get realtime response
- Disable slack when it is not configured
- NOT a breaking change, compatible with previous releases
- Icons have been cloned as SVG files from the [Figma file provided](https://www.figma.com/file/o0Cljct8qmt1qvsN22b4dh/Komiser?type=design&node-id=3-17527&t=lTRlRO4zWb7Z1BqN-0).
- The userflow is exactly as per the [Loom video](https://www.loom.com/share/797b4255476444cc9583d65e2a237a7b).
- New DeleteAlertView Component has been created as per the designs
- Post request's body is for the test endpoint is:
```json
{
  "view": "Test Connection",
  "message": "Cost alert",
  "from": "Komiser"
}
```
- Post request's body is for an alert message is:
```json
{
  "view": "rich",
  "message": "Cost alert",
  "cost": 0.08381685558808585
}
```
- View controller to track and manage the user state for alerts
- Variables across the dashboard have been renamed to a conventional `alert` from `slackAlert`
- Naming conventions 
    - **alertMethod**: is the alert a CustomWebhook or Slack
    - **alertType**: is the alert Budget or Usage
- The **alert** table in the database sees a new field called `isSlack` for each alert to distinguish the method.

## How to Test
- Slack:
    1. Do not pass the Slack webhook in config and make sure that the option is disabled but you are able to set the webhook alert
    2. Now pass the slack webhook in config and make sure you are able to set both slack and webhook alerts
    3. Verify the slack alert in the hook you have provided in config
- Custom Webhook:
    1. Use https://webhook.site/ to get a custom webhook URL for yourself
    2. Create a new custom webhook alert from the UI and pass the custom webhook URL you received from above.
    3. Hit on test endpoint and see it getting validated
    4. Pass a Secret now and create the webhook.
    5. Once the cronjob runs again, you should be able to see the secret as a Req Header in the webhook receiver.

## Screenshots
- Will make a walkthrough screen recording and put it up for easier verification!

## Notes
- Add documentation for the POST request body format that we make once agreed upon by the team.
- I wasn't able to run `go-bindata-assetfs -o template.go dist/ dist/assets/images/` so if any of the maintainers can help me by running that for me on this PR, it'd be really helpful (maintainers have edit access to this).

PS: This was my first time dealing with React as well as Next so do let me know if by any chance any anti-practice is followed (I tried my best not to!). 🥂 to a productive weekend haha!

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary **NONE**

2023-05-30 07:40 UTC, mlabouardy requested changes
@ShubhamPalriwala if the user tried to create a Slack alert on an existing `alerts` table, the following error is returned:
![Screenshot 2023-05-30 at 09 38 59](https://github.com/tailwarden/komiser/assets/10320205/e62f1a26-8ed5-4741-b4e9-abe57e120274)
This can be fixed by writing a migration script to add `isSlack` column (if doesn't exists) to the table upon Komiser launch (see [example](https://github.com/tailwarden/komiser/blob/master/migrations/20230413100000_set_default_tags_in_resources.go))

2023-05-30 07:48 UTC, mlabouardy commented on models/alert.go
> +	IsSlack  bool    `json:"isSlack"`
I would add a `bun` to this field as well for readability since it will be created as `is_slack` in the database

2023-05-30 07:49 UTC, mlabouardy commented on internal/api/v1/endpoints.go
> +	router.POST("/testendpoint", api.TestEndpointHandler)
personal nitpick: I would put rename it to `/alerts/test` just to have all alerting endpoints under alerts subpath

2023-05-30 07:52 UTC, mlabouardy requested changes

2023-05-30 07:52 UTC, mlabouardy commented on handlers/alerts_handler.go
> +func (handler *ApiHandler) DoAlertsExistHandler(c *gin.Context) {
maybe I'm missing something but I think this endpoint isn't needed, you could use this [one](https://github.com/tailwarden/komiser/blob/b84e8d8b12dd85c73ff45b5de9bdc1d9bb7537fb/handlers/views_handler.go#L147) to get view's alerts

2023-05-31 11:57 UTC, ShubhamPalriwala commented on models/alert.go
> +	IsSlack  bool    `json:"isSlack"`
thanks for this, handled!

2023-05-31 12:01 UTC, ShubhamPalriwala commented on handlers/alerts_handler.go
> +func (handler *ApiHandler) DoAlertsExistHandler(c *gin.Context) {
oh great catch, this **should** be view specific yeah! my mistake here :/ thanks a ton, on it

2023-05-31 12:09 UTC, ShubhamPalriwala commented on handlers/alerts_handler.go
> +func (handler *ApiHandler) DoAlertsExistHandler(c *gin.Context) {
this was an existing bug that I did not notice that could have been reproduced if:
- I setup alerts for a view
- Switch to a different view that does not have any alerts setup

The alert for this page would then just be on the loading page. :////

Thanks a ton @mlabouardy for pointing this out, fixed it!

2023-05-31 12:41 UTC, ShubhamPalriwala commented
hi @mlabouardy, I have made the request changes except for the migration script, can you help me with that please :/

2023-06-03 16:35 UTC, mlabouardy approved these changes
LGTM 🚀

2023-06-03 16:37 UTC, merged