Addedd Dependency graph for AWS EC2 and EIP
tailwarden/komiser pull request #849
Opened 2023-06-10 15:46 UTC by AvineshTripathi

Currently pushing this branch to see if it is fit to review and maybe we could start initial reviews!

Note:  Will add description soon!

2023-06-14 06:41 UTC, mlabouardy requested changes
Great job @AvineshTripathi 👏🏻  I've few comments to improve code readability :) 
 
Also, I wasn't able to display the graph even though I had EC2 instances running in my AWS account:
<img width="1465" alt="Screenshot 2023-06-14 at 08 39 51" src="https://github.com/tailwarden/komiser/assets/10320205/6af193aa-fc9d-4f8e-b0bc-235f634b2c4e">
<img width="1146" alt="Screenshot 2023-06-14 at 08 40 48" src="https://github.com/tailwarden/komiser/assets/10320205/f19d04b4-68ba-4c0f-b046-edd84edda01f">

2023-06-14 06:41 UTC, mlabouardy commented on dashboard/pages/dashboard.tsx
> +        <DashboardDependencyGraphWrapper />
I would move it to a dedicated page under "Explorer": 
![image](https://github.com/tailwarden/komiser/assets/10320205/6f711929-4c18-4572-b640-a129703c44cd)

2023-06-14 06:41 UTC, mlabouardy commented on dashboard/package.json
> +    "d3-selection": "^3.0.0",
are `d3-selection`, `elkjs` and `web-worker` needed?

2023-06-14 06:41 UTC, mlabouardy commented on dashboard/components/dashboard/components/dependency-graph/nodes/nodes.tsx
> +  switch (label) {
I would keep it simple and instead of returning the logo of each cloud service, I would return the cloud provider logo that way the function will be simple (and not huge) and we don't need to worry about cloud services without a logo

2023-06-14 06:41 UTC, mlabouardy commented on dashboard/services/settingsService.ts
> +      const res = await fetch(`${BASE_URL}/views/relations`, settings('GET'));
why its under `/views` and not `/resources`

2023-06-14 06:41 UTC, mlabouardy commented on handlers/views_handler.go
> +func (handler *ApiHandler) RelationStatsHandler(c *gin.Context) {
I would move it to `resources_handler` since you're interacting with `resources` table

2023-06-14 06:41 UTC, mlabouardy commented on internal/api/v1/endpoints.go
> +	router.GET("/views/relations", api.RelationStatsHandler)
same here about `/resources/relations`

2023-06-14 06:48 UTC, AvineshTripathi commented on dashboard/package.json
> +    "d3-selection": "^3.0.0",
Yep they are as I think under the hood we were using d3-selection for some other component and elkjs is what giving us dynamic layout and it also uses the d3 and due to which there was version conflicts and to avoid that I had to put it in pakcage.json. I am down to remove this if there are no versioning issue and no errors of web-worker

2023-06-14 07:13 UTC, AvineshTripathi commented on dashboard/pages/dashboard.tsx
> +        <DashboardDependencyGraphWrapper />
Do you think adding only one component to a new page is a good option instead when we have another component ready then we can move this too. Thoughts?

2023-06-14 07:14 UTC, AvineshTripathi commented on dashboard/services/settingsService.ts
> +      const res = await fetch(`${BASE_URL}/views/relations`, settings('GET'));
I was not sure about how the divison was made so. I'll fix this acc

2023-06-19 12:29 UTC, mlabouardy commented
Hey @AvineshTripathi let us know once those fixes are done so we can proceed with the PR :)

2023-06-20 10:18 UTC, mlabouardy requested changes

2023-06-20 10:18 UTC, mlabouardy commented on handlers/resources_handler.go
> +	err := handler.db.NewRaw("SELECT DISTINCT resources.resource_id, resources.service, resources.relations FROM resources WHERE (json_array_length(relations) > 0)").Scan(handler.ctx, &output)
depending on the connected database (SQLite or PG) the query is slightly different, you can use the following:
```
query := "SELECT DISTINCT resources.resource_id, resources.service, resources.relations FROM resources WHERE (jsonb_array_length(relations) > 0)"
if handler.db.Dialect().Name() == dialect.SQLite {
   query = "SELECT DISTINCT resources.resource_id, resources.service, resources.relations FROM resources WHERE (json_array_length(relations) > 0)"
}
```

2023-06-20 10:18 UTC, mlabouardy commented on migrations/20230619100000_add_new_relation_field.go
> +		db.ExecContext(ctx, "ALTER TABLE resources ADD COLUMN relations JSONB DEFAULT '{}'::jsonb;")
my bad, the default value should be an array, not an object :)
`ALTER TABLE resources ADD COLUMN relations JSONB DEFAULT '[]'::jsonb;`

2023-06-23 09:32 UTC, mlabouardy requested changes
I'm getting the following error now when I'm using Postgres:
![Screenshot 2023-06-23 at 11 29 44](https://github.com/tailwarden/komiser/assets/10320205/8ef36fc9-e08d-46e9-bf99-117208033931)

2023-06-24 08:04 UTC, ShubhamPalriwala commented
@AvineshTripathi, looks like the issue Mohamed faced can be avoided in the future if we migrate away from the `any` and use strict typecasting.
Let me know if you are up for it, would be glad to collaborate in any way and help get this feature get the most out of TS.

Also, let's sync up so we can also start adding the support across all the AWS resources we support!

Let me know what you think of it

2023-06-24 10:20 UTC, AvineshTripathi commented
@ShubhamPalriwala this is backend error and mainly a postgresql however for frontend the error can be removed by changing func to ForEach instaed map

2023-06-24 11:51 UTC, ShubhamPalriwala commented
As far as I think, the error is basically because the runtime does not know the type of the `nodes` variable. If we type it strictly, we would get that error (and if others) at the compile time itself and we would handle it there itself resulting in a smoother runtime experience!

2023-06-24 12:39 UTC, AvineshTripathi commented
Sure lets assign types to all. However I am currently moving towards a very compact schedule so I dont think I'll have bandwidth to resolve this for now. I am open to anyone to take this branch and add the proper ts support.

Also I am still struggling to setup postgresql to replicate the error so help in that is appreciated

2023-06-28 08:05 UTC, mlabouardy commented
> Sure lets assign types to all. However I am currently moving towards a very compact schedule so I dont think I'll have bandwidth to resolve this for now. I am open to anyone to take this branch and add the proper ts support.
> 
> Also I am still struggling to setup postgresql to replicate the error so help in that is appreciated

maybe you could add the types to this PR @ShubhamPalriwala ?

2023-06-28 16:03 UTC, ShubhamPalriwala commented
yessir, will do next and ping here once done!

2023-06-28 16:59 UTC, AvineshTripathi commented
I made an attempt to resolve it in one go today that was not a perfect attempt though but it did give me idea about blockers so please ping me if you need help with the code explanation or some weird errors(I did came across those) @ShubhamPalriwala

2023-07-04 16:09 UTC, closed without merging