feat: fixed toast ui
tailwarden/komiser pull request #862
Opened 2023-06-19 13:13 UTC by Oluwaseyi3

## Problem

The icon wasn't aligned with the text  in the toast UI. It also needed some padding 

## Changes Made

I worked on the UI based the Figma model and reconciled the differences with Tailwind CSS

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

![toast](https://github.com/tailwarden/komiser/assets/72235523/224e0186-26dc-4464-82b6-eb2f9f90b783)

## Reviewers

@mlabouardy

2023-06-21 09:56 UTC, mlabouardy requested changes
Thanks @Oluwaseyi3, a small change and we should be good :)

2023-06-21 09:56 UTC, mlabouardy commented on dashboard/components/toast/Toast.tsx
> +            <p className="pb-2 text-xl font-medium">{title}</p>
can you revert to text-sm as the title is quite huge :) 
![image](https://github.com/tailwarden/komiser/assets/10320205/ae2b2e09-462b-4391-8047-650bed1b83c2)

2023-06-21 10:52 UTC, Oluwaseyi3 commented on dashboard/components/toast/Toast.tsx
> +            <p className="pb-2 text-xl font-medium">{title}</p>
Alright. On it Mohamed!

2023-06-21 13:37 UTC, Oluwaseyi3 commented on dashboard/components/toast/Toast.tsx
> +            <p className="pb-2 text-xl font-medium">{title}</p>
Hi @mlabouardy I set it to text-lg and it looks perfectly okay for a title. Just a bit bigger than the text body. You can check it out. 



![hh](https://github.com/tailwarden/komiser/assets/72235523/46d99e0b-dd8a-46e4-89f9-6721382e9096)

If you still want it to be reviewed pls don't hesitate to notify me

2023-06-21 17:20 UTC, mlabouardy commented on dashboard/components/toast/Toast.tsx
> +            <p className="pb-2 text-xl font-medium">{title}</p>
all good then :)

2023-06-21 17:20 UTC, mlabouardy approved these changes
Thanks for the changes @Oluwaseyi3 :)

2023-06-21 18:03 UTC, mlabouardy commented
> Thanks for the changes @Oluwaseyi3 :)

seems like CI failed due to package.json changes, could you check that @Oluwaseyi3 
https://github.com/tailwarden/komiser/actions/runs/5334667306/jobs/9672597140?pr=862

2023-06-21 18:07 UTC, Oluwaseyi3 commented
> > Thanks for the changes @Oluwaseyi3 :)
> 
> seems like CI failed due to package.json changes, could you check that @Oluwaseyi3 https://github.com/tailwarden/komiser/actions/runs/5334667306/jobs/9672597140?pr=862

Alright. Will correct that asap

2023-06-22 13:38 UTC, Oluwaseyi3 commented
> > > Thanks for the changes @Oluwaseyi3 :)
> > 
> > 
> > seems like CI failed due to package.json changes, could you check that @Oluwaseyi3 https://github.com/tailwarden/komiser/actions/runs/5334667306/jobs/9672597140?pr=862
> 
> Alright. Will correct that asap



> > > Thanks for the changes @Oluwaseyi3 :)
> > 
> > 
> > seems like CI failed due to package.json changes, could you check that @Oluwaseyi3 https://github.com/tailwarden/komiser/actions/runs/5334667306/jobs/9672597140?pr=862
> 
> Alright. Will correct that asap

@mlabouardy Pls you can check it out now. I updated the package.json. Let me know if the test cli passes

2023-06-23 11:10 UTC, Oluwaseyi3 commented
> > > > Thanks for the changes @Oluwaseyi3 :)
> > > 
> > > 
> > > seems like CI failed due to package.json changes, could you check that @Oluwaseyi3 https://github.com/tailwarden/komiser/actions/runs/5334667306/jobs/9672597140?pr=862
> > 
> > 
> > Alright. Will correct that asap
> 
> > > > Thanks for the changes @Oluwaseyi3 :)
> > > 
> > > 
> > > seems like CI failed due to package.json changes, could you check that @Oluwaseyi3 https://github.com/tailwarden/komiser/actions/runs/5334667306/jobs/9672597140?pr=862
> > 
> > 
> > Alright. Will correct that asap
> 
> @mlabouardy Pls you can check it out now. I updated the package.json. Let me know if the test cli passes




Hi @mlabouardy just noticed it failed once more. I’ve installed a new package.lock. This one is in sync with the develop branch. This would work now

2023-06-24 08:18 UTC, ShubhamPalriwala requested changes
Hey @Oluwaseyi3, I can still see a lot of package-lock.json changes in the git diff hence why the build is failing due to dependency mismatch.

One suggestion for a cleaner and quicker fix would be to remove the `package-lock.json` from the git tracking of this PR and just add and commit the `dashboard/components/toast/Toast.tsx` file, this should solve it all at once and the PR should be good to merge then

2023-06-24 11:03 UTC, Oluwaseyi3 commented
> Hey @Oluwaseyi3, I can still see a lot of package-lock.json changes in the git diff hence why the build is failing due to dependency mismatch.
> 
> One suggestion for a cleaner and quicker fix would be to remove the `package-lock.json` from the git tracking of this PR and just add and commit the `dashboard/components/toast/Toast.tsx` file, this should solve it all at once and the PR should be good to merge then

On it

2023-06-25 20:04 UTC, Oluwaseyi3 commented
> Hey @Oluwaseyi3, I can still see a lot of package-lock.json changes in the git diff hence why the build is failing due to dependency mismatch.
> 
> One suggestion for a cleaner and quicker fix would be to remove the `package-lock.json` from the git tracking of this PR and just add and commit the `dashboard/components/toast/Toast.tsx` file, this should solve it all at once and the PR should be good to merge then

All done @ShubhamPalriwala

2023-06-27 07:47 UTC, merged