Dependency graph another attempt
tailwarden/komiser pull request #883
Opened 2023-07-07 09:33 UTC by AvineshTripathi

2023-07-12 11:16 UTC, mlabouardy requested changes

2023-07-12 11:16 UTC, mlabouardy commented on dashboard/package.json
> +    "reactflow": "^11.7.2",
can you also remove it from deps?

2023-07-13 14:48 UTC, ShubhamPalriwala requested changes
Hey @AvineshTripathi, the PR looks good to me! 👍🏼 just a small nit from my end if you could take a look! @mlabouardy can you review once and then we can proceed further 🤞🏼

2023-07-13 14:53 UTC, AvineshTripathi commented on providers/aws/ec2/security_groups.go
The reason I removed this was because for aws there is no resourcearn for security groups

2023-07-13 14:55 UTC, ShubhamPalriwala commented on providers/aws/ec2/security_groups.go
okay then! gtg from my end 😊

2023-07-13 14:55 UTC, ShubhamPalriwala approved these changes

2023-07-13 15:53 UTC, mlabouardy approved these changes
Perfect, great job :)

2023-07-15 08:22 UTC, merged