Linode lke #818
tailwarden/komiser pull request #904
Opened 2023-07-24 01:21 UTC by professorabhay

## Problem

https://github.com/tailwarden/komiser/issues/818

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@ShubhamPalriwala and @mlabouardy

2023-07-26 16:42 UTC, mlabouardy approved these changes

2023-07-26 16:44 UTC, ShubhamPalriwala requested changes
LGTM thanks to @mlabouardy! 🚀 
hey @professorabhay just suggested a couple of small nits (apologies for asking such small changes), once done, we can proceed and merge the PR!

2023-07-26 16:44 UTC, ShubhamPalriwala commented on providers/linode/lkepool/lke_pool.go
> +			// Region:     nodePool.Region,
can we either add this or remove this for better code quality?

2023-07-26 16:44 UTC, ShubhamPalriwala commented on providers/linode/lkepool/lke_pool.go
> +			// Add any additional fields or data you want to collect here.
and remove this comment as well?

2023-07-26 16:44 UTC, ShubhamPalriwala commented on providers/linode/lkepool/lke_pool.go
> +			CreatedAt:  time.Time{}, // Update this with the actual created time.
can we fix this please if possible?

2023-07-27 08:27 UTC, professorabhay commented on providers/linode/lkepool/lke_pool.go
> +			CreatedAt:  time.Time{}, // Update this with the actual created time.
I tried but not find the way to do so. Because every time I try to fetch then its give error of not defined in linodego library

2023-08-01 05:16 UTC, ShubhamPalriwala commented on providers/linode/lkepool/lke_pool.go
> +			CreatedAt:  time.Time{}, // Update this with the actual created time.
Then can we have some other identifier if possible as a name? or if you could fetch the name in some other way and parse it? because ideally we should not **not have a name**. Let me know if you need my hand on this!

2023-08-02 04:28 UTC, professorabhay commented on providers/linode/lkepool/lke_pool.go
> +			CreatedAt:  time.Time{}, // Update this with the actual created time.
Ok, I'll let you know

2023-08-26 10:04 UTC, ShubhamPalriwala commented
Hey @professorabhay, any update on this please? If you are unable to get the node name, can you add any other identifier as a name? Because we cannot keep that field blank, we can possibly tackle the name at a later stage! Let me know once the PR is ready for review!

2023-08-26 10:43 UTC, professorabhay commented
Hey @ShubhamPalriwala, I make the changes as you said. 
As, I read the official code of the library name is not return in the object. 
![image](https://github.com/tailwarden/komiser/assets/76243309/93b66070-873b-437f-9b70-1c3884a67e4f)
[LINK](https://github.com/linode/linodego/blob/28949e59aeae084304f2185e38b58359d435c0c1/lke_node_pools.go#L23)

2023-08-26 10:56 UTC, ShubhamPalriwala commented
Okay, so can you add something like an ID to the name field of the Komiser object for a comparatively better identification? Thanks

2023-08-26 14:08 UTC, professorabhay commented
![Screenshot_2023-08-26-19-35-10-971_com.github.android.png](https://github.com/tailwarden/komiser/assets/76243309/b5ab8e01-2295-4981-9422-a807395d3578)

I added `type` because the `id` is fetched in the resource id as per above img. I think that if both fields will same then it create confusion in understanding. But if you still want the update then I can give it a try 🙂

2023-08-31 04:34 UTC, AvineshTripathi commented
We donot have a standard for now so I would suggest keeping id is better, but @ShubhamPalriwala I think we should work together and write down what exactly this field in the resources should carry

2023-08-31 08:36 UTC, mlabouardy commented
> We donot have a standard for now so I would suggest keeping id is better, but @ShubhamPalriwala I think we should work together and write down what exactly this field in the resources should carry

Great suggestion, happy to help with that as well :)

2023-09-15 09:42 UTC, merged