fix(814) Add instance disks resource to linode
tailwarden/komiser pull request #911
Opened 2023-08-14 14:35 UTC by titanventura

## Problem

Support instance disks - Linode

## Solution

Added instance disks to the list of resources under linodes function.

## Changes Made

- Modified the linode provider to include instance disks

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines

## Reviewers

@jakepage91 @mlabouardy 

fixes #814

2023-08-16 04:47 UTC, mlabouardy commented
@AvineshTripathi @ShubhamPalriwala wdyt?

2023-08-17 02:44 UTC, titanventura commented on providers/linode/compute/instances.go
> +		"service":   "Linode and Instance Disk",
Usually, they call linode instances as linodes. But if `linode instance and instance disk` seems to sound good, we can go with that ! 
WDYT ?

2023-08-18 06:10 UTC, AvineshTripathi commented on providers/linode/compute/instances.go
> +				Service:    "Instance Disk",
Should we rename this to `Linodes Instance disk` as the Service field is generally showed on Komiser dashboard, so do you think specifying is better?

2023-08-18 06:11 UTC, AvineshTripathi commented on providers/linode/compute/instances.go
> +		"service":   "Linode and Instance Disk",
I'll leave it upto you if you say so I dont mind. Also did you check it in dashboard if the Linodes and Instance disks are separetly created as two different entity?

2023-08-24 15:28 UTC, titanventura commented on providers/linode/compute/instances.go
> +		"service":   "Linode and Instance Disk",
Hey, I think it won't be displayed in the dashboard because the `FetchDataFunction` for Linode is actually commented out, IDK why

Reference: https://github.com/tailwarden/komiser/blob/57bbd94ae975fcb18daf822e8f1687eaace3eac8/providers/linode/linode.go#L21

2023-08-26 10:07 UTC, ShubhamPalriwala requested changes
Hey @titanventura, the PR looks good to me! I just think you forgot to call the service so once that is fixed, we can merge the PR!

2023-08-26 10:07 UTC, ShubhamPalriwala commented on providers/linode/linode.go
> +		// compute.LinodeInstancesAndInstanceDisks,
Did you forget to uncomment this?

2023-08-27 08:41 UTC, titanventura commented on providers/linode/linode.go
> +		// compute.LinodeInstancesAndInstanceDisks,
this line was uncommented before i started working on this PR, i changed the name of the function so made changes to this line as well, anyways the problem is that `compute.Linodes` or `compute.LinodeInstancesAndInstanceDisks` does not comply with `providers.FetchDataFunction` interface, because of the third parameter !

2023-09-07 08:52 UTC, AvineshTripathi commented on providers/linode/compute/instances.go
> +		"service":   "Linode and Instance Disk",
You would have to uncomment that

2023-09-09 17:23 UTC, titanventura commented
Enabled the FetchData function for Instance and Instance disks and also implemented changes suggested in comments.

Please review @AvineshTripathi @mlabouardy @ShubhamPalriwala .

Also, had one more suggestion, currently, the instance disks are dependant on the instance resources in linode, as a result of this, the fetching of instance disks happens synchronously, should we have an option in komiser that enables concurrent fetching of nested reources. If we implement this, a similar pattern can be followed for other nested resources as well. Adding some concurrency would improve the fetching speed. Just a suggestion, if approved, would be happy to try this in a separate PR for the same resource. :)

2023-09-10 03:16 UTC, AvineshTripathi commented
Hey @titanventura we are currently looking to redesign the arch of komiser where one of most important things to add is concurrent fetching of resources. If you are willing to help me with brainstorming how we do that all together would definitely like to collaborate.

2023-09-10 03:20 UTC, titanventura commented
For sure @AvineshTripathi , I'd be more than happy to collaborate!

2023-09-12 08:46 UTC, mlabouardy approved these changes
LGTM!

2023-09-12 09:49 UTC, merged

2023-09-12 19:35 UTC, AvineshTripathi commented
hey @titanventura can yo dm me over discord n we connect n work on arch/