Feature/552 eventsubscription
tailwarden/komiser pull request #928
Opened 2023-08-28 22:50 UTC by datadeverik

## Problem

Fixes #552 

## Solution

Add eventsubscription

## Changes Made

Add support for Amazon Redshift eventsubscription

## How to Test

I created an eventSubscription through the awscli, then checked that it appeared in the Komiser UI.

## Screenshots

![Screen Shot 2023-08-28 at 5 33 21 PM](https://github.com/tailwarden/komiser/assets/52926724/f11ccfe7-c95f-4549-87e9-e2b59d6bef9f)

## Notes

I indicated in comments in the code some points I'm not sure about. Also, testing and documentation isn't done, but I wanted to get some eyes on what I've done so far. Also, I used `go get go get github.com/aws/aws-sdk-go-v2/service/redshift`, which I noticed changed various version numbers. I'm not sure if this is what we want at this point.

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-08-29 15:09 UTC, mlabouardy requested changes
Hey @datadeverik, thanks for the PR
I've left some minor comments

2023-08-29 15:09 UTC, mlabouardy commented on providers/aws/redshift/eventsubscription.go
> +func EventSubscription(ctx context.Context, client ProviderClient) ([]Resource, error) {
can we change it to plural form "EventSubscriptions" ?

2023-08-29 15:09 UTC, mlabouardy commented on providers/aws/redshift/eventsubscription.go
> +		for _, eventSubscription := range output.EventSubscriptionsList { // TODO: capitalization convention?
yes

2023-08-29 15:09 UTC, mlabouardy commented on providers/aws/redshift/eventsubscription.go
> +		if aws.ToString(output.Marker) == "" { // TODO: is output.Marker here playing the same role as ouput.NextMarker in the efs example?
exactly

2023-08-29 15:09 UTC, mlabouardy commented on providers/aws/redshift/eventsubscription.go
> +					Service:    "Redshift",
Redshift EventSubscription?

2023-08-30 19:56 UTC, AvineshTripathi commented on providers/aws/redshift/eventsubscription.go
> +				outputTags, err := redshiftClient.DescribeTags(ctx, &redshift.DescribeTagsInput{
I think we can get tags directly from output and so would not need DescribTags

2023-08-30 20:38 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +func EventSubscription(ctx context.Context, client ProviderClient) ([]Resource, error) {
I will change it, yes.

2023-08-30 20:40 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +					Service:    "Redshift",
Oh okay, right. That makes more sense.

2023-08-30 20:40 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +		"service":   "Redshift",
Yes

2023-08-30 20:56 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +				monthlyCost := float64(0) // TODO: what is the monthly cost
I don't know how to determine the monthly cost for this.

2023-08-31 04:27 UTC, AvineshTripathi reviewed
LGTM

2023-08-31 04:27 UTC, AvineshTripathi commented on providers/aws/redshift/eventsubscription.go
> +		if aws.ToString(output.Marker) == "" {
Should we add a logger? for debugging purposes?

2023-08-31 16:09 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +		if aws.ToString(output.Marker) == "" {
I'll look around for examples of loggers in a similar positions in existing functions.

2023-09-01 09:02 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +				monthlyCost := float64(0) // TODO: what is the monthly cost
After a discussion with @jakepage91 , I am going to simply set cost to zero, because this service does not directly incur costs.

2023-09-01 09:08 UTC, datadeverik commented on providers/aws/redshift/eventsubscription.go
> +		if aws.ToString(output.Marker) == "" {
After some basic inspection, I don't see a logger in similar places in existing functions in the AWS provider. (like for example `providers/aws/lambda/functions.go`).

But now it occurs to me that maybe you were suggesting adding a logger temporarily to answer the question in the comment, namely "TODO: is output.Marker here playing the same role as ouput.NextMarker in the efs example?".

In any case, it seems that the feature is working correctly, so maybe there isn't a need to pursue this point further.

2023-09-01 14:14 UTC, AvineshTripathi commented on providers/aws/redshift/eventsubscription.go
> +		if aws.ToString(output.Marker) == "" {
Sounds good to me I think we are ready to go with this!

2023-09-01 14:19 UTC, mlabouardy approved these changes

2023-09-01 14:20 UTC, merged