Update alerts.mdx
tailwarden/komiser pull request #963
Opened 2023-09-14 16:23 UTC by akshayamadhuri

## Problem

issue: #947 
## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-09-15 04:34 UTC, shivam-sharma7 requested changes
Remove these extra lines

2023-09-15 04:36 UTC, shivam-sharma7 commented on docs/guides/alerts.mdx
> +
```suggestion






















```

2023-09-15 04:37 UTC, shivam-sharma7 requested changes

2023-09-15 04:37 UTC, shivam-sharma7 commented on docs/guides/alerts.mdx
> +
remove these extra lines

2023-09-16 19:59 UTC, AvineshTripathi commented
Tagging @jakepage91 for review

2023-09-19 09:49 UTC, merged