feat: feedback collection backend
tailwarden/komiser pull request #988
Opened 2023-09-22 12:21 UTC by AvineshTripathi

2023-09-22 12:44 UTC, shivam-sharma7 approved these changes
FYI

2023-09-22 12:45 UTC, shivam-sharma7 commented
@AvineshTripathi FYI

```go
     defer resp.Body.Close()

	// Check response status
	if resp.StatusCode != http.StatusOK {
		logrus.WithField("StatusCode", resp.StatusCode).Error("Feedback request failed")
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Feedback request failed"})
		return
	}

	// Return a success message
	c.JSON(http.StatusOK, gin.H{"message": "Feedback sent successfully"})
}

2023-09-22 12:47 UTC, AvineshTripathi commented
@shivam-sharma7 didn't get you also it's not ready for review, am still working on this

2023-09-24 16:31 UTC, Azanul requested changes

2023-09-24 16:31 UTC, Azanul commented on handlers/feedback_handler.go
> +	}`, description, email)
Using a struct instead of an Sprintf would be more idiomatic

2023-09-24 16:31 UTC, Azanul commented on handlers/feedback_handler.go
> +	var url = ""
empty url

2023-09-25 15:13 UTC, AvineshTripathi commented on handlers/feedback_handler.go
> +	}`, description, email)
Since the only change in above structure is email and description variable, having a struct will be of no use as would would have to marshal/unmarshal it which I found of no use here. Thoughts? cc @mlabouardy

2023-09-25 15:50 UTC, Azanul commented on handlers/feedback_handler.go
> +	}`, description, email)
Using a struct here would make it easier to extend and maintain the payload as compared to the formatted string.
With that being said, it is fine while the only fields while we only care about `email` and `description` only.

2023-09-25 15:56 UTC, Azanul commented on handlers/feedback_handler.go
> +	var url = ""
I do not have the context here but from the payload it looks like we're trying to hit a Discord webhook but it's url is not mentioned, which would probably be passed through the config.

2023-09-25 16:41 UTC, AvineshTripathi commented on handlers/feedback_handler.go
> +	}`, description, email)
this is one part of the feature and will have a separate PR for frontend so I want to keep the payload be something handled along with frontend. Thanks for the feedback will keep it in mind!

2023-09-25 16:41 UTC, AvineshTripathi commented on handlers/feedback_handler.go
> +	var url = ""
Correct I did the change, hopefully it works cause that is not tested ;)

2023-09-26 08:46 UTC, Azanul commented on handlers/feedback_handler.go
> +	}`, description, email)
If you plan on handling the payload construction in the front end then it's fine. Personally, I wouldn't have done it that way but that's just me.

2023-09-26 08:47 UTC, Azanul approved these changes

2023-09-26 09:08 UTC, AvineshTripathi commented on handlers/feedback_handler.go
> +	}`, description, email)
Nope payload will be handled in backend itself, but we might need to do changes in the structure like maybe adding new fields or stuff but that will come when work in the frontend starts. Sorry for confusion

2023-09-26 12:31 UTC, mlabouardy approved these changes

2023-09-26 12:31 UTC, merged