feat: allow user to connect multiple cloud accounts
tailwarden/komiser pull request #989
Opened 2023-09-22 19:24 UTC by greghub

## Problem

[Provide a brief description of the problem that you are trying to solve with this pull request.]

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

2023-09-23 01:02 UTC, shivam-sharma7 requested changes

2023-09-23 01:02 UTC, shivam-sharma7 commented on dashboard/pages/onboarding/cloud-accounts/index.tsx
> +                  alt="AWS"
```suggestion
                  src={providers.providerImg('gcp')}
                  className="h-full w-full"
                  alt="GCP"
```

2023-09-23 01:02 UTC, shivam-sharma7 commented on dashboard/pages/onboarding/cloud-accounts/index.tsx
> +                  alt="AWS"
change alt name

2023-09-23 01:02 UTC, shivam-sharma7 commented on dashboard/pages/onboarding/cloud-accounts/index.tsx
> +                  alt="AWS"
here as well

2023-09-27 09:20 UTC, Kolawole99 commented on dashboard/pages/onboarding/cloud-accounts/index.tsx
> +import Head from 'next/head';
The change in this file seems to me like a duplication of the landing page of the cloud account, right?

2023-09-29 05:03 UTC, greghub commented on dashboard/pages/onboarding/cloud-accounts/index.tsx
> +import Head from 'next/head';
I'm not sure I understood the question

2023-09-29 05:06 UTC, greghub commented
@mlabouardy please check if the payloads are correct (you can do it in dashboard/utils/cloudAccountHelpers.ts). 

Also, a few things are missing since I didn't know what to put there:
- [ ] Correct placeholder values resembling real API keys for MongoDB atlas and Scaleway
- [ ] Descriptions for Scaleway, Tencent, Linode, and MongoDB onboarding pages

2023-09-29 09:26 UTC, Traxmaxx commented on dashboard/pages/onboarding/provider/aws.tsx
> +import Toast from '../../../components/toast/Toast';
Can we update the imports maybe? We added the following paths to tsconfig recently and this makes it so much easier to move around files 

```
      "@components/*": ["components/*"],
      "@services/*": ["services/*"],
      "@environments/*": ["environments/*"],
      "@utils/*": ["utils/*"],
      "@styles/*": ["styles/*"]
```

2023-09-29 09:26 UTC, Traxmaxx commented on dashboard/pages/onboarding/provider/gcp.tsx
> +import useToast from '../../../components/toast/hooks/useToast';
Same here for paths

2023-09-29 09:26 UTC, Traxmaxx commented on dashboard/pages/onboarding/provider/linode.tsx
> +export default function LinodeCredentials() {
This file looks awfully similar to the GCP one. I'm sure you looked into unifying them, what's the reason we have a template per provider instead of parameterizing a single one with props?

2023-09-29 09:36 UTC, Traxmaxx commented on dashboard/utils/cloudAccountHelpers.ts
> +export interface AWSCredentials extends Credentials {
Why extending an empty interface? We should at least put the shared stuff in the to be extended interface. Also why interface and not type? Types have name collition while interfaces have not

2023-09-29 11:55 UTC, Traxmaxx commented on dashboard/components/account-details/AzureAccountDetails.tsx
> +                stroke-linejoin="round"
the other values need to change as well, the console should show where to update them

2023-09-29 11:56 UTC, Traxmaxx commented
![image](https://github.com/tailwarden/komiser/assets/320272/4324d962-64ba-4dfc-94c1-944cf563eadf)
SQLite shows Postgres toast

2023-09-29 11:59 UTC, Traxmaxx commented on dashboard/components/onboarding-wizard/LabelledInput.tsx
>          <input
This input throws

```
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
input
div
div
InputFileSelect@webpack-internal:///./components/onboarding-wizard/InputFileSelect.tsx:11:171
```

2023-10-02 19:26 UTC, mlabouardy requested changes
@greghub are you planning to address the above comments?

2023-10-03 12:25 UTC, greghub commented on dashboard/utils/cloudAccountHelpers.ts
> +export interface AWSCredentials extends Credentials {
I am extending it in order to be able to use both `cloudAccountData?: CloudAccountPayload<AWSCredentials>;` and `  cloudAccountData?: CloudAccountPayload<Credentials>;`

2023-10-03 12:28 UTC, greghub commented
@mlabouardy all issues addressed + more fixes + more refactors. ready to review

2023-10-03 12:52 UTC, mlabouardy commented
> @mlabouardy all issues addressed + more fixes + more refactors. ready to review

on it :)

2023-10-03 13:01 UTC, shivam-sharma7 commented on dashboard/components/account-details/AwsAccountDetails.tsx
> +              handleInputChange={e => setFile(e.target.value)}
```suggestion
              handleInputChange={(e) => setFile(e.target.value)}
```

2023-10-03 13:02 UTC, shivam-sharma7 approved these changes

2023-10-03 13:02 UTC, shivam-sharma7 commented on dashboard/components/account-details/AwsAccountDetails.tsx
> +              handleInputChange={e => setFile(e.target.value)}
@greghub WDTY?

2023-10-03 13:34 UTC, shivam-sharma7 commented on dashboard/components/account-details/AwsAccountDetails.tsx
> +              handleInputChange={e => setFile(e.target.value)}
@greghub WDYT?

2023-10-03 13:55 UTC, AvineshTripathi commented on dashboard/components/layout/Layout.tsx
> +  const betaFlagOnboardingWizard = true; // To test the onboarding wizard feature, set this beta-flag to true
We can remove the comment

2023-10-03 15:01 UTC, greghub commented on dashboard/components/account-details/AwsAccountDetails.tsx
> +              handleInputChange={e => setFile(e.target.value)}
I don't mind but we use just `e` in several other places in the app. We could discuss and decide to replace everywhere with `(e)` in a separate ticket

2023-10-04 08:52 UTC, Kolawole99 approved these changes
LGTM

2023-10-04 09:11 UTC, mlabouardy approved these changes
All good!

2023-10-04 09:13 UTC, merged