Metric Stream cost calculation
tailwarden/komiser pull request #990
Opened 2023-09-23 04:15 UTC by Azanul

## Problem

Issue #878 

## Solution

`metric stream cost = update cost * no. of updates`

Fetching `MetricUpdate` cost using pricing API and update count using cloudwatch statistics API.

ref:
- [CloudWatch-metric-streams-monitoring](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-monitoring.html)
- [CloudWatch Pricing](https://aws.amazon.com/cloudwatch/pricing/)

## Changes Made

- Added function for fetching `pricePerUnit` from `GetProductsOutput`.
- Added cost calculation for Metric Streams.

## Notes

- Ignored the AWS Kinesis Data Firehose surcharge

## Checklist

- [X] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [X] Any dependencies have been added to the project, if necessary

## Reviewers

@mlabouardy 
@ShubhamPalriwala

2023-09-24 14:53 UTC, mlabouardy requested changes
Thanks @Azanul for the PR. I requested a small change before merging the PR :)

2023-09-24 14:53 UTC, mlabouardy commented on providers/aws/cloudwatch/log_metrics.go
> +	metricUpdateRateCode = "VJDTMA8S4PDEWU6J.JRTCKXETXF.6YS6EN2CT7"
this should be dynamic since its different from one AWS account to another. On my account its: `22982JCS3SFJKUVZ.JRTCKXETXF.6YS6EN2CT7`

2023-09-24 16:05 UTC, Azanul commented on providers/aws/cloudwatch/log_metrics.go
> +	metricUpdateRateCode = "VJDTMA8S4PDEWU6J.JRTCKXETXF.6YS6EN2CT7"
alarms cost calculation also has hardcoded ratecoded, shall I fix that as well?

2023-09-25 11:49 UTC, mlabouardy commented on providers/aws/cloudwatch/log_metrics.go
> +	metricUpdateRateCode = "VJDTMA8S4PDEWU6J.JRTCKXETXF.6YS6EN2CT7"
yes please 🙏🏻

2023-09-26 08:37 UTC, mlabouardy approved these changes
LGTM!

2023-09-26 08:37 UTC, merged